### ISSUE TITLE
Aiming is totally broken in 1.16 version.

### ISSUE THREAD

**Issue by M0niak** [MrCrayfish/Controllable#100]
Sometimes looking left or right looks up or down, diagonals are reversed sometimes, it's totally messed up.

Using Xbox One controller.

**Comment by iCeCoCaCoLa64** [comment]
Same thing happens to me with my PS4 controller. Hope this gets fixed quickly.

**Comment by ETGAMING** [comment]
I also have this problem on my Xbox One Bluetooth Controller. I would also like to add that the buttons are mapped incorrectly for Xbox Controllers. Please get back to us on this issue as soon as possible as it has been over a month.

**Comment by M0niak** [comment]
aiming still broke, haywire

**Comment by M0niak** [comment]
please fix
