### ISSUE TITLE
Can't play with split screen.

### ISSUE THREAD

**Issue by ximocm** [MrCrayfish/Controllable#102]
Whesn I'm playing with two screens, and one loses its focus, it stop working and I can't click on back to game.

Minecraft 1.16
Forge 32.0.98
Latest mod update downloaded from curseforge.
Windows 10
16gb Ram 
Ryzen 7 3750h
RTX 2060
Using PS4 controller

**Comment by MrCrayfish** [comment]
Turn off Pause of unfocus (F3 + P) and make sure both use virtual mouse.
