### ISSUE TITLE
Game crashes at startup on macos 10.11 [Minecraft 1.16.1]

### ISSUE THREAD

**Issue by joshuaorgeron** [MrCrayfish/Controllable#103]
Whenever I connect my xbox one controller the game crashes in the middle of startup.

**Comment by joshuaorgeron** [comment]
Heres the log:

**Comment by joshuaorgeron** [comment]
https://pastebin.com/8wGXn9ew

**Comment by MrCrayfish** [comment]
Is this an issue on 0.10.1?

**Comment by nicogig** [comment]
> Is this an issue on 0.10.1?

Yes, I am having the same issue on macOS Big Sur (11.1) on Minecraft 1.16.3 with an Xbox One Bluetooth Controller.

**Comment by MrCrayfish** [comment]
I mean Controllable 0.10.1

**Comment by MrCrayfish** [comment]
This may be an issue with GLFW and not something I can fix in my mod. It seems https://github.com/glfw/glfw/issues/1763 is having the problem with the same controller. Are you using wired or wireless (Bluetooth)?

**Comment by nicogig** [comment]
> This may be an issue with GLFW and not something I can fix in my mod. It seems [glfw/glfw#1763](https://github.com/glfw/glfw/issues/1763) is having the problem with the same controller. Are you using wired or wireless (Bluetooth)?

Yeah just looked into that, It could very well be. I'm using Bluetooth, not sure about the OP.

**Comment by MrCrayfish** [comment]
I'm going to close this issue, but I will update if any fix comes at in the future. Let me know if USB works.
