### ISSUE TITLE
Mouse Problems

### ISSUE THREAD

**Issue by MATRIXMMLG** [MrCrayfish/Controllable#105]
alright this going to be hard to explain but were ever i start my curser at well when every i go to a different area of the screen it will teleport back if i move even slightly towards it. it only happens when im out of the game play like when i open the inventory when i open settings everything does it except when im playing its so ANNYOING. other wise i really like it but i just cant use it because of this.

**Comment by Dexislay** [comment]
I believe this is caused by a conflict with Optifine, try running it without Optifine to test if it is fixed.
