### ISSUE TITLE
Chinese translation submission

### ISSUE THREAD

**Issue by ZTZTJun** [MrCrayfish/Controllable#106]
Hello! I am a China game player.
I really like the mod you made, because it adds support to the handle. Chinese game player Chinese language translation, but I found that there is no simplified Chinese translation (only the traditional Chinese translation), so for many China players, language barriers cause them to be unable to use this mod, so I want to add simplified Chinese language support to your mod. :)

- Lang files
`controllable.action.break=破坏
controllable.action.attack=攻击
controllable.action.eat=进食
controllable.action.drink=饮用
controllable.action.block=防御
controllable.action.pull_bow=拉弓
controllable.action.place_block=放置方块
controllable.action.use_item=使用物品
controllable.action.interact=互动
controllable.action.inventory=打开物品栏
controllable.action.close_inventory=关闭物品栏
controllable.action.swap_hands=交换左右手物品
controllable.action.dismount=取消骑乘
controllable.action.jump=跳跃
controllable.action.sneak=潜行
controllable.action.drop_item=扔掉物品
controllable.action.pickup_stack=拾起一组物品
controllable.action.pickup_item=拾起物品
controllable.action.quick_move=快速移动
controllable.action.place_stack=放置一组物品
controllable.action.place_item=放置物品
controllable.gui.title.select_controller=选择一个控制器
controllable.gui.select=选择
controllable.gui.configure=配置
controllable.gui.cancel=取消
controllable.toast.controller=控制器
controllable.toast.connected=已连接
controllable.toast.disconnected=未连接`

- Json files
`{
  "controllable.action.break": "破坏",
  "controllable.action.attack": "攻擊",
  "controllable.action.eat": "攻击",
  "controllable.action.drink": "饮用",
  "controllable.action.block": "防御",
  "controllable.action.pull_bow": "拉弓",
  "controllable.action.place_block": "放置方块",
  "controllable.action.use_item": "使用物品",
  "controllable.action.interact": "互动",
  "controllable.action.inventory": "打开物品栏",
  "controllable.action.close_inventory": "关闭物品栏",
  "controllable.action.swap_hands": "交换左右手物品",
  "controllable.action.dismount": "取消骑乘",
  "controllable.action.jump": "跳跃",
  "controllable.action.sneak": "潛行",
  "controllable.action.drop_item": "扔掉物品",
  "controllable.action.pickup_stack": "拾起一组物品",
  "controllable.action.pickup_item": "拾起物品",
  "controllable.action.quick_move": "快速移动",
  "controllable.action.place_stack": "放置一组物品",
  "controllable.action.place_item": "放置物品",
  "controllable.gui.title.select_controller": "选择一个控制器",
  "controllable.gui.select": "选择",
  "controllable.gui.configure": "配置",
  "controllable.gui.cancel": "取消",
  "controllable.toast.controller": "控制器",
  "controllable.toast.connected": "已连接",
  "controllable.toast.disconnected": "未连接"
}`

**Comment by ZTZTJun** [comment]
Finally, I want to say,
Plz! Please add fabric support! Adding fabric may make your mod more popular!

**Comment by JukoiDev** [comment]
@ZTZTJun It is not easy to port mod to never used modloader, also **_FORGE 4EVER_**
