### ISSUE TITLE
Split screen doesn’t work

### ISSUE THREAD

**Issue by Billybobertjoe** [MrCrayfish/Controllable#107]
When trying split screen with an xbox controller for one screen and a keyboard and mouse for the other, when I try using the mouse on the keyboard and mouse window, the controllers window pauses and i can’t unpause it without pausing my keyboard and mouses window and unpausing it with the mouse and the cycle repeats. Please fix

**Comment by MrCrayfish** [comment]
You need to turn "pause on unfocus" off. Press F3 + P
