### ISSUE TITLE
Controllable Crashing Game.

### ISSUE THREAD

**Issue by Extendoz** [MrCrayfish/Controllable#108]
I cannot get this mod to work, I have tried many things other than removing all my other mods first. 
Forge 1.12.2  14.23.5.2854
controllable-1.12.2-0.8.0

I attached the crash report.

[crash-2020-08-27_23.12.50-client.txt](https://github.com/MrCrayfish/Controllable/files/5139834/crash-2020-08-27_23.12.50-client.txt)

**Comment by MrCrayfish** [comment]
I don't maintain 1.12.2 anymore. You'll have to switch to an earlier version (< 0.8.0) to fix this issue.
