### ISSUE TITLE
controllable takes full control of your controller, just like steam

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [MrCrayfish/Controllable#115]
when controllable detects a controller, it takes full control of it, which, like steam, may cause issues with other programs, namely DSUClients (see #113), causing inputs to be falsely detected in both programs

**Comment by MrCrayfish** [comment]
Can you explain what DSU Clients are? Both Google and DuckDuckGO yield no useful results. It seems like something this mod is not designed to support.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
clients that virtualize DS4s over a server but with motion controls and a touchpad (mainly used in emulators of consoles with motion controls), and can also virtualize XInput,
here are all the ones for windows
here are all the ones for windows:
Switch controllers - BetterJoy - https://github.com/Davidobot/BetterJoy
DualShock 4 - DS4Windows - https://github.com/Ryochan7/DS4Windows
WiiMoteHook - https://github.com/epigramx/WiimoteHook
SteamGyroForCemuhook - https://github.com/FrogTheFrog/steam-gyro-for-cemuhook

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
you can also use a controller over the internet with those

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
issues like this are the reason HIDGuardian exists, but it just doesn't seem to work

**Comment by MrCrayfish** [comment]
I'm still confused at what needs to be "fixed". Turn off auto select in the options if you don't want the controller selected automatically. DS4Windows works fine with Controllable. It sounds like a large scale issue and not directly Controllable.
