### ISSUE TITLE
DPAD left/right are reversed

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [MrCrayfish/Controllable#116]

**Comment by MrCrayfish** [comment]
I need more info. Works perfectly fine for me

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
the icons for dpad left and right are swapped

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
that's it

**Comment by MrCrayfish** [comment]
I need more info... Which controller icons?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
DPad left and DPad right are swapped, so if i map something to dpad left, it has the dpad right icon, and if i map it to dpad right, it has the dpad left icon

**Comment by MrCrayfish** [comment]
At least send a screenshot

**Comment by MrCrayfish** [comment]
0.10.1 now offers the ability to remap buttons.
