### ISSUE TITLE
Cannot hit Resume Game with the Controller, when playing two instances of Minecraft.

### ISSUE THREAD

**Issue by WLafleur07** [MrCrayfish/Controllable#117]
I am trying to play two instances Minecraft 1.16.1, one using KB + M and the other using a Xbox One joystick. The one using KB+M works fine, but the one using the Controlled Mod won't let me hit Resume Game while using the Gamepad

**Comment by MisterFox1986** [comment]
YES! I have the same problem..
I do not know what to do. Thought the problem was due to mods, but no.

**Comment by Dexislay** [comment]
you'll need to hit F3 + P to disable the auto-pause when the window loses focus. That'll keep it from pausing the second instance when you switch back to the first.
