### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by Haymaker969** [MrCrayfish/Controllable#118]
When i open my inventory, and pick up an item, it goes to wherever my mouse cursor is, since im using nucleuscoop to play split screen i cant use my mouse. This makes using the inventory extremely tedious.

**Comment by MrCrayfish** [comment]
You don't need extra tools to play splitscreen. Controllable already provides this functionality. Make sure "Pause on Unfocus"
 is turned off by pressing F3 + P and make sure you use virtual mouse for both instances.
