### ISSUE TITLE
Unable to add Controllable support to other mods

### ISSUE THREAD

**Issue by N3ROO** [MrCrayfish/Controllable#119]
The Controllable .jar and .pom can not be found. Here is what I added to my `build.gradle`:

```build.gradle
repositories {
    maven {
        name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }
}

dependencies {
    compile 'controllable:Controllable:1.12.1:0.2.1'
}

minecraft {
    useDepAts = true
}
```

Even changing `1.12.1:0.2.1` to `1.12.1-0.2.1` won't fix this issue. I wanted to use the 1.16.3 version (so 1.16.3:0.8.3), but it won't work either.

I tried to reach the URL manually : `https://minecraft.curseforge.com/api/maven/controllable/Controllable/1.16.3-0.8.3/Controllable-1.16.3-0.8.3.jar` (also with 1.12.1) but it says resource not found.

**Comment by MrCrayfish** [comment]
```gradle
repositories {
    maven {
        url = "https://www.cursemaven.com"
    }
}

dependencies {
    compile fg.deobf('curse.maven:controllable:<curseforge_file_id>')
}
```

You can find the ID of the file by looking at the url on CurseForge
`https://www.curseforge.com/minecraft/mc-mods/<slug>/files/<curseforge_file_id>`
`https://www.curseforge.com/minecraft/mc-mods/controllable/files/3068902`
