### ISSUE TITLE
Works with Nintendo Switch Pro Controller on MacOS but... 

### ISSUE THREAD

**Issue by UnlikePaladin98** [MrCrayfish/Controllable#12]
It connects as it should but for some reason my character keeps moving backwards for no reason even when there was no input from the controller nor keyboard (I noticed that even after the 5 second time during which the overlay should have disappeared it was still there, so the game must be thinking that some button is still pressed)
A link to a clip of what happens: [link](https://drive.google.com/file/d/1tZFoMm6oV7ZYwhOE0kKXXwIxsYUxNZCS/view?usp=sharing)

EDIT: replaced the word works for connects
EDIT 2: Still happens when the mod is alone. Also noticed that the sensitivity for the right joystick is really low (changing to hyperspeed from normal settings doesn't affect it)

**Comment by MrCrayfish** [comment]
Download 0.4.0, this has been fixed. Customize the dead zone to your liking in the controllable settings menu when selecting your controller.
