### ISSUE TITLE
Does not function with hori gamepad mini ps4 controller

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MrCrayfish/Controllable#124]
I had to buy a smaller controller for my daughter because she cannot use the bigger full size controllers, so I got this https://www.amazon.com/Mini-Wired-Gamepad-HORI-playstation-4/dp/B01A6MKVAA and whenever I use your mod past 1.12.2 I get an issue where camera is always forced up. I did some diagnotics on the controller sticks and it turns out they are 100% okay. Its just your mod. I am not why just the right stick is acting weird I have tried unbinding it. Also mind you the GUI for bindings is also not working for this either I manually changed things. I like the idea of letting my daughter play "Minecraft Java Edition" but if the game has no controller support that is not going to happen.

**Comment by MrCrayfish** [comment]
Change the deadzone in Controllable settings. You can find the settings menu in the selection menu for the controller.

**Comment by P3rf3ctXZer0** [comment]
I tried that a ton of times can you be a bit more specific?

**Comment by P3rf3ctXZer0** [comment]
Also how does that fix "fixed ghosting?" There is nothing wrong with the controller. 
![WZapB3d 1](https://user-images.githubusercontent.com/10351221/100364766-2b363380-2fc4-11eb-838f-e9188c2b8cc1.gif)

**Comment by MrCrayfish** [comment]
Is this an issue with other controllers or just this one? Try setting the deadzone to 0 in DS4Windows and set the deadzone in Controllable settings instead.

Also can you try this version of the mod? https://www.dropbox.com/s/1rbgzy325pdf2s8/controllable-1.16.3-0.8.4.jar?dl=0
I've enabled the "Remap" button. This will take you to a screen where you can visually see your input in the mod. Note that this is not a working feature yet to remap buttons/sticks. Let me know what is going on when you look at your input. Send a screenshot if possible.

**Comment by P3rf3ctXZer0** [comment]
So if it is any indication it seems to work completely fine for 1.12.2 specifically version https://www.curseforge.com/minecraft/mc-mods/controllable/files/2880163

**Comment by MrCrayfish** [comment]
Did you see my reply?

**Comment by P3rf3ctXZer0** [comment]
yeah I don't have time right now for extensive testing. It works with "Pixelmon Evolved" and that is all I need right now.
