### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by sophienix** [MrCrayfish/Controllable#127]
help i cant remap my buttons i tried every controller i have and its still not working i even
 tried other versions
 ![image_2020-12-12_192207](https://user-images.githubusercontent.com/74495871/101999881-5486dd00-3caf-11eb-8328-7e2d185a36ab.png)

**Comment by matt328** [comment]
Same here, i'm guessing it's not ready yet.  In the config folder there is a folder called `mappings`.  Can we even drop a file in there and have it work, or is none of that implemented yet?

**Comment by sophienix** [comment]
its working now but i got rid of it cause i couldn't edit my controls for
the keyboard i couldn't find a way to edit them with the mod on unless you
know how to then please tell me

**Comment by sophienix** [comment]
oops wrong mod

**Comment by sophienix** [comment]
no you can config them I seen other people do it it just wont work for me

**Comment by MrCrayfish** [comment]
You can now change bindings and mapping in 0.10.1
