### ISSUE TITLE
Paper Doll On screen at all times

### ISSUE THREAD

**Issue by Simmikke** [MrCrayfish/Controllable#129]
I'm using Minecraft 1.12.2 with the accompanying version. Just installed this mod to use with an Xbox One controller, registers perfectly fine, however, is there a way to turn off the paper doll in the left corner of the screen? I'm not sure if it's an intentional feature. Attempting to turn it off using F8 doesn't work either. (Screen is dark due to taking a screenshot)

![image](https://user-images.githubusercontent.com/76635100/103161826-dc3b1400-47a4-11eb-9175-f22b9aadac7a.png)

Edit: Additional Issue, I also can't configure the controller at all. Is this because it's an older version?

**Comment by MrCrayfish** [comment]
Turn off in Controllable settings menu.
