### ISSUE TITLE
Not detecting xbox one Bluetooth controller

### ISSUE THREAD

**Issue by stripedspot** [MrCrayfish/Controllable#130]
OS:Ubuntu x86_64
Kernel: 5.4.0-58-generic
Using a blue tooth controller to play minecraft, I need this mod so I can do this.
The controller is detected. and connected but not in minecraft.

**Comment by MrCrayfish** [comment]
Is this still an issue on the latest version? (0.10.1)

**Comment by vkrazzi** [comment]
> Is this still an issue on the latest version? (0.10.1)

I am playing on 1.16.5 and my Xbox One wired and Xbox One wireless controllers are both not being detected by the mod but they are detected by steam. Any Suggestions on a fix?

I also forgot to add I previously had it working and playable before but it is no longer working

**Comment by MrCrayfish** [comment]
I've written a full documentation for Controllable which can help with different methods of connecting controllers and troubleshooting issues on Linux: https://mrcrayfish.gitbook.io/controllable-documentation/
