### ISSUE TITLE
Gameplay Features bugs

### ISSUE THREAD

**Issue by 2009XboxLiveKid** [MrCrayfish/Controllable#134]
A feature that seems to be missing, which is a key feature in console is the ability to move
through your inventory with the D-Pad, which had been non existent since I've used this mod.
-------
*The Quick move feature is now non functional, and non existent in the button bindings window,
along with any time you rebind a button on the D-Pad (Xbox One) left and rights are swapped.
(Icon wise)
*Exiting your inventory is also bugged. After picking up an item in your 
inventory, it will not allow
you to exit the inventory.
*When you switch around the buttons bindings, the buttons shown on screen do not change from the default
![bug](https://user-images.githubusercontent.com/58410886/105913958-7f6c8c80-5fe2-11eb-9ecb-3f344926bc53.PNG)
![bug1-2](https://user-images.githubusercontent.com/58410886/105913960-7f6c8c80-5fe2-11eb-9a3d-0059ed691cfb.PNG)

**Comment by MrCrayfish** [comment]
Thanks for the report. Are you able to create seperate issues for each problem as this will help get these solved quicker? Thank you

**Comment by MrCrayfish** [comment]
This is a feature now
