### ISSUE TITLE
Why is this mod getting worse with every update?

### ISSUE THREAD

**Issue by DanKruse731** [MrCrayfish/Controllable#135]
Summer 2019, I managed to get decent use out of this mod, and I was hoping for the experience to be improved with more features and polished controls. Sadly, this mod has not made any progress over the past year and a half and yet the new version (0.9.1) actually renders the game unplayable.

(These issues were found using an Xinput controller)
- Actions that require holding down the triggers don't work. (Eating, mining, etc.)
- The virtual mouse option is useless because the mouse ends up breaking the menus and crafting interface.
- The crafting interface is still a mess, with the mouse automatically hovering to the center of the closest slot.
- The mod still doesn't have D-Pad crafting, which would've gone a long way to improving the experience.

I am simply disappointed that this mod has made no progress whatsoever, and the latest version being this broken is pathetic. It's as if this mod isn't being properly tested or even cared about. I just want to play the arguably definitive version of Minecraft with a controller in hand, and given my experiences with this mod, it looks like I will have to wait even longer for this to become a viable solution.

**Comment by MrCrayfish** [comment]
I'm sorry you've had a bad experience with the mod. I definitely know there is room for improvement for the experience but the issues relating to virtual mouse breaking menus or triggers not working is not something I have encounted during testing. If you can please report theses problems as individual issues with more details that would be of great help. I unfortuantely only have limited time when developing this mod and this recent update was highly overdue.

**Comment by DanKruse731** [comment]
If anything, I should be apologizing for my harsh tone. Sorry about that.
I do hope for the best for Controllable, given this mod has been the best remedy for controller support thus far.
I'll keep an eye on this project, because with time, I have faith it will become an enjoyable solution that me and my friends will get a use out of.
Keep up the great work!

P.S.
The issues I were having were tested with a Wireless Xbox One Controller.

**Comment by MrCrayfish** [comment]
Are you able to try out 0.10.1 and let me know if your experience has been improved?
```
Controllable 0.10.1 Changlog:
+ Now using GLFW to handle controller input. This also reduces the mod size to 200kb.
+ It is now possible to navigate around GUI and inventory with DPAD buttons.
+ You can now scroll throw recipe book tabs and pages with new button bindings (use bumpers and triggers)
+ Added an option to control available actions on the HUD. (All, Mininal or Off)
+ Better integration with JEI
* Fixed mouse drifting slight after being released
* Fixed mouse moving to incorrect position of slots when recipe book is open
```
