### ISSUE TITLE
Block breaking issues in 1.16

### ISSUE THREAD

**Issue by ArronIsCringe** [MrCrayfish/Controllable#137]
When I try and break blocks survival Steve will do one hit and stop

I went back and tried it on 1.14.4 to check im not crazy and it did indeed work there

**Comment by CerealTheSauS** [comment]
I've been having this issue too. It's not just breaking blocks, but anything that has to do with holding down triggers it's really annoying. A game breaking bug in an otherwise almost perfect controller support mod :(

**Comment by lights0123** [comment]
Here's the problem, my guess is that `clickMouse` is a single click

 https://github.com/MrCrayfish/Controllable/blob/8fb43f3ae22a7ea87968f18a293263c472bf9031/src/main/java/com/mrcrayfish/controllable/client/ControllerInput.java#L631-L634

**Comment by lights0123** [comment]
Ah, this has actually been fixed in the latest version. @ArronIsCringe and @CerealTheSauS [go download the latest version](https://github.com/MrCrayfish/Controllable/releases).

**Comment by MrCrayfish** [comment]
If someone else (who experienced the problem) can confirm this has been fixed I will close this issue.

**Comment by jadenPete** [comment]
Hello, I experienced the problem with 0.9.x and it's fixed now.

**Comment by ArronIsCringe** [comment]
I can confirm that this issues has been fixed in the newest build, thanks for the quick work mrcrayfish

**Comment by MrCrayfish** [comment]
Thank you guys!

**Comment by wonkywalkie** [comment]
Sorry to be a bummer, but I'm having the same issue on a completely fresh install.
Minecraft 1.15.2
Forge 31.2.0
Controllable 0.11.1
Windows 10 Home
PS4 controller with DS4

I really hoped the issue was that I had been using the controller via Bluetooth, but via USB doesn't seem to improve things.

Let me know what other details you need

**Comment by MrCrayfish** [comment]
Upgrade to Forge 31.2.45 if using 1.15.2

**Comment by wonkywalkie** [comment]
> Upgrade to Forge 31.2.45 or above if using 1.15.2. I should really make that a requirement.

A compatibility list would go a long way for noobs like me.
Thank you for a speedy response and easy fix!

**Comment by MrCrayfish** [comment]
I have pushed a new patch that will require 31.2.45 or higher to be installed.
