### ISSUE TITLE
Look and Move aren't stopping

### ISSUE THREAD

**Issue by Silky-Chillz** [MrCrayfish/Controllable#14]
I am using a brand new Sony Duel Shock 4 controller connected through usb, and I found that whenever I use one of the analog sticks, it sometimes doesn't stop reading it in-game. If I stop moving the stick, I keep moving forward and looking down very slowly. I found that this only happens when I slowly release the analog sticks, and only doesn't happen when I forcefully jab the sticks. I hope that this can be fixed. Other than this, tremendous job with this mod! 👍

**Comment by MrCrayfish** [comment]
Download 0.4.0. I added support to change the deadzone.
