### ISSUE TITLE
Inventory Works Odd.

### ISSUE THREAD

**Issue by Floobah** [MrCrayfish/Controllable#144]
When I use the inventory, items tend to move around as they want to with controllable. Especially with then a keyboard and mouse.
If I move an item to a specific slot, the items tend to split the stack and move into either the chest inventory or the player inventory at random. 

Not sure why this is happening, I also use inventory tweaks renewed and optifine but the issue seems to lie solely with Controllable.

1.16.5 forge 36.0.1

**Comment by MrCrayfish** [comment]
Thanks for the report! I've done some testing and have run into the issue you have described. I will get a fix out soon.
