### ISSUE TITLE
If i play with old version i cant look up or down but in latest version it is not detecting my controllers 

### ISSUE THREAD

**Issue by Oslamb** [MrCrayfish/Controllable#146]

**Comment by MrCrayfish** [comment]
What controller are you using?

**Comment by Oslamb** [comment]
That's  pc controllers
Dx Usb joysticks

**Comment by Oslamb** [comment]
> What controller are you using?

That's pc controllers
Dx USB joysticks

**Comment by MrCrayfish** [comment]
You can't use a joystick, only gamepads.

**Comment by Oslamb** [comment]
> You can't use a joystick, only gamepads.

Same issue with gamepad either
Plz help If you want i can send you screen shots

**Comment by MrCrayfish** [comment]
Which gamepad are you using?

**Comment by Oslamb** [comment]
> Which gamepad are you using?

thats pc controllers

Wired Vibration Gamepad PC USB Controller Gampad  (White)

**Comment by Oslamb** [comment]
> Which gamepad are you using?

Double Shock pc Controllers 
That;s pc controllers 

and on old version i can play easily but cant look up or down

**Comment by Oslamb** [comment]
> Which gamepad are you using?

Help me plz
