### ISSUE TITLE
Works almost perfectly, but lack of deadzone makes it unusable

### ISSUE THREAD

**Issue by RadGH** [MrCrayfish/Controllable#15]
Using an xbox one controller that works well in most games, but both of my xbox one controllers like to drag to the edge after moving or turning. There's no way to change the deadzone in windows, or even the Xbox Accessories app which does have some settings -- but no deadzone option.

I tried launching Minecraft through Steam (actually through Twitch, so it was confusingly Steam > Twitch > Minecraft). This let me use Steam's wonderful customization options including deadzone (interior, exterior, and anti deadzones) via the steam overlay. But the mod was incapable of recognizing the controller from Steam and ended up crashing when I went to the controller list (index out of bound error). I tried launching through steam's Big Picture mode too, but had the same issue (no controller detected, controller list menu crashing).

Adding support for Steam configs or a setting to change the deadzone should fix the problem. I know other people mentioned deadzones before, but wanted to add my feedback.

Thanks for the effort so far! It does seem very polished other than a couple bugs (and I know it's still in development).

**Comment by MrCrayfish** [comment]
I've now implemented deadzone customisation in the latest version (0.4.0). I will be porting to 1.12.2 soon, right now only available on 1.14.4.

**Comment by RadGH** [comment]
@MrCrayfish Thanks for adding the feature. Would really love to see it ported back to 1.12.2. I know that's probably very low on your priorities especially compared to the awesome new features in the furniture mod. 

I would love to show some support for the mod and maybe give a little encouragement for the port to 1.12.2, but I don't see a way to send a donation for your efforts. Do you accept donations?
