### ISSUE TITLE
X and Y buttons cannot be flipped/Switch controller icons/Change what the open inventory button does when in the inventory

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#153]
When flipping what X and Y are bound to (so orientation and icons match for switch controller,) both buttons are unable to be used at all. (X doesn't open or close inventory, Y doesn't swap hands) Also, it'd be nice to have a controller icon set for the switch controller, as it works when using bluetooth (Wired is a different story, blame windows and it's shoddy button registration) 

Another thing, it'd be nice to be able to use the B button to close the inventory/Back out of menus rather than the inventory button again, since that's what bedrock edition does. i can't imagine the amount of times i accidentally closed the inventory trying to quick move an item or quick moved something from my hotbar when i tried to close the inventory.

**Comment by MrCrayfish** [comment]
Are you using the bindings menu or the layout menu? If using the layout menu, it's not designed for rebinding actions, it's simply to configure the mappings so Controllable has a standard input. The "physical" positions of the buttons on your controller should match the visual controller. If you're using it to match to the icons, you're using it wrong.

Make sure in the layout menu you don't have any warnings. This means the button has no mapping to a physical button on the controller and therefore won't work at all.
![image](https://user-images.githubusercontent.com/4958241/107727330-f58b2600-6d3a-11eb-9722-72c2c1d17c11.png)

In the bindings menu, if any bindings have red text, it means there is a conflict and it won't work.
![image](https://user-images.githubusercontent.com/4958241/107727449-4569ed00-6d3b-11eb-9baf-fd95c577c70e.png)

In terms of configuring the close inventory, I can probably add a new binding for that. I'll let you know when it's added.

**Comment by dude98** [comment]
if that's the case, could you also add a "flip X and Y Icons" or add a switch icon set that does so?
Also, i'd appreciate it if you could have the "show icons in inventroy" and "show icons ingame" as seperate toggles as well.
Other than that, i really appreciate you doing so, and this mod is still amazing. (A and B are flipped in layout for me since it makes sense to me due to switch version's bindings, but if you did the same to them as the X and Y buttons, it'd be perfect, that is, if you do decide to do it, considering the icons would definitely take a little to make.)

**Comment by dude98** [comment]
Moved into seperate issues, closing this one for later.
