### ISSUE TITLE
Can't mine, can't select anything in inventory/menu

### ISSUE THREAD

**Issue by Kainaluking** [MrCrayfish/Controllable#155]
I'm playing on the newest version and when I hold down right trigger it triggers once but won't continue mining, and in the menu and inventory screens the cursor is only able to navigate in the top quarter of the screen and can't select anything.

**Comment by MrCrayfish** [comment]
Can you please let me know which version of the mod your are using? Also which Forge version? If using 1.15.2, make sure you are using at least Forge 31.2.45
