### ISSUE TITLE
Other mods overlap controller icons

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#156]
Mods like JEI overlap the icon to close/open inventory, and some mods for the ingame overlap with the mine/place block buttons
(Inventory HUD Plus, Although that's just because i have the inventory in the bottom left) it'd be nice to be able to move the controller icon lists to an unused corner of the screen (bottom left only for inventory, bottom right only for ingame) even if it was just a option and not freely moveable.

**Comment by MrCrayfish** [comment]
I'll see what I can do. What you have suggested is just a bandaid solution to a bigger problem, once another mod decides to render something on the other side, where would the icons go besides completely gone? At most I can provide better support for JEI as it's the most popular mod but not any other mod.
