### ISSUE TITLE
Disable Dpad Inventory Movement Sound Effect And Add Left Stick Radial Movement And Add Alternate Activate Radial Selection

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#158]
The clicking noise that plays when you move the cursor with the dpad can get very irritating if you only use the dpad to move your inventory around. having a way to disable it would be very much appreciated.

**Comment by MrCrayfish** [comment]
Will add an option in the next update

**Comment by dude98** [comment]
Bringing this back into thought since you might've forgot about it, that radial menu's still a great addition though, but i'd appreciate it if there was an option to allow left stick to navigate radial, and add a "activate radial option" separately too, since it stays highlighted when you move the stick back, and having my X button which is "Switch Off Hand" turn into that button when radial is up would be beneficial since my steam controller's mouse like joystick mode isn't the greatest for a radial menu.
Still, this mod is going great, let me know if i should split this into separate issues or if this is fine, keep doing your amazing work.

**Comment by MrCrayfish** [comment]
Please create a new issue instead of renaming title

**Comment by MrCrayfish** [comment]
Also added an option to disable sound in 0.13.0
