### ISSUE TITLE
Inventory browser partially functional on macOS

### ISSUE THREAD

**Issue by mjquinn21** [MrCrayfish/Controllable#16]
The inventory opens and closes when triangle is pressed, the L and R triggers tab through the different menus as they should, and scrolling using Up and Down on the D-Pad works fine. The only issue is that the pointer reverts to its initial position on the screen after releasing the left thumb stick and moving it again.

So, if you can’t quite get it to hover over the item that you need, you have no way of letting go, readjusting, then moving it over a smidge. This happens all throughout the game (i.e. in crafting interfaces, on the main menu, and in the settings), but it is most noticeably in game.

It doesn’t hinder me aside from driving me a little crazy because I play in Creative but it would be fairly gamebreaking in some situations in Survival.

I have no reason to suspect this but my premonition is that it is a result of either the Force Trackpad or the macOS trackpad drivers. This issue does not arise using Steam Big Picture or other keymapping software. 

Not sure if it would be possible to make it so that instead moving the cursor the left stick just moves through the grid box by box, but that would be good to add as a toggle.
——————————
Running Controllable 0.3.1 for Minecraft 1.12.2 on macOS 10.14.5. 
Don’t know my version of Forge off the top of my head but I can get it for you if need be.

**Comment by MrCrayfish** [comment]
Try using 0.4.0 with 1.14.4. Minecraft now uses LWJGL 3.0 and GLFW which I'm prettu sure now standardises the mouse position. Closing this for now, create a new issue if this is still a problem on 0.4.0 or above.
