### ISSUE TITLE
When I connect Xbox Wireless Controller to Mac the game crashes.

### ISSUE THREAD

**Issue by BlaBlaBlico** [MrCrayfish/Controllable#160]
There is some error that pops-up when I connect my controller to my Mac with bluetooth. Keep in mind that while the controller is not connected the game starts together with the mod with no issues.

The game crashed whilst initializing game
Error: java.lang.IllegalStateException: GLFW error before init: [0x10004]Invalid button in gamepad mapping 030000005e040000fd02000003090000 (Xbox Wireless Controller)
Exit Code: 255

Attaching the full crash report:
[crash-2021-02-27_11.24.39-client.txt](https://github.com/MrCrayfish/Controllable/files/6054101/crash-2021-02-27_11.24.39-client.txt)

**Comment by MrCrayfish** [comment]
This is a GLFW issue, not something I can fix in Controllable unfortunately. May be related to https://github.com/glfw/glfw/issues/1763
