### ISSUE TITLE
Helpull Feature

### ISSUE THREAD

**Issue by 2009XboxLiveKid** [MrCrayfish/Controllable#162]
Could we please get the feature of being able to close the inventory for hitting the "B" or "Square" button? but only if the interface isnt clicked onto an item.

Ex: picks up item, and moves the curser off the inventory screen to drop it using the B or Square button, but is able to back out of the inventory/any interface by pressing B.

OR creating Controller Profiles based on either Bedrock Default controls, or Legacy Default controls

**Comment by MrCrayfish** [comment]
A separate binding has been added to Controllable to close inventories. As for a dropping items outside the inventory screen, you just need to use the same button you used to pick it up.
