### ISSUE TITLE
Cursor mapping to the one quarter of the screen.

### ISSUE THREAD

**Issue by dropbrick** [MrCrayfish/Controllable#164]
Hi,
I'm using a 8bit do SN30 and it connects fine when in the "Pro" or "Wireless" controllers mode. 

Only problem: the cursor mapping is wrong. I can only move the cursor on the top left quarter of the image... mouse mapping instead is ok.

IS there a config file somewhere ? Or is there a specific resolution to run at ? Using Minecraft Java on  MacOS here.

Thanks!

**Comment by dropbrick** [comment]
This actually works ok in full screen mode. It's in the window mode that it doesn't.


Unfortunately I fear this controller has not enough buttons to use Minecraft well ? (e.g. not sure how to look around... like when you use the mouse.)

**Comment by MrCrayfish** [comment]
Should be fixed. I am guessing you have a Retina display, that's what caused the issue but I fixed it now.

**Comment by skyerday** [comment]
Hi,
I am in the same symptom too with 1.16.5 & MacBook Pro 16" & 8bitdo SN30 pro controller.

minecraft: 1.16.5
launcher: MultiMC
forge: 36.1.0
Controllable: 0.13.3
