### ISSUE TITLE
Inventory item box cursor appearing only when 2 monitors are attached

### ISSUE THREAD

**Issue by valentyn-l** [MrCrayfish/Controllable#165]
Hello! 

I ran into a bug where the square cursor that surrounds an item in the inventory only appears when I connect a second monitor to the computer. I've attached a screenshot with the square cursor around the flint resource. 

With one monitor, the default cross cursor just overlays on top of the item instead blocking the visibility of the item. 

![InkedUntitled_LI](https://user-images.githubusercontent.com/60371520/110463402-26f4d880-80d2-11eb-85ad-fce2a40aab39.jpg)

**Comment by MrCrayfish** [comment]
Is this still an issue in the latest version? I have made multiple patches related to Optifine compat which this falls under.

**Comment by valentyn-l** [comment]
Partially, yes. If I go into a menu and move the cursor with the left stick, the square cursor appears. If after opening a menu I start selecting items with the D-Pad, the crosshair cursor appears instead of the square cursor.

**Comment by MrCrayfish** [comment]
I am going to need more information. Which version of the mod are you using? Which version of Minecraft are you using? What are the exact steps to reproduce? (A picture doesn't tell me anything as it looks like normal behaviour)

**Comment by MrCrayfish** [comment]
If this is still an issue on modern versions of Controllable (1.19+), feel free to reopen a new issue.
