### ISSUE TITLE
Windows cursor always on top of the Minecraft window, even in fullscreen

### ISSUE THREAD

**Issue by valentyn-l** [MrCrayfish/Controllable#166]
Hello!

I wanted to make a request to have the ability to hide the Windows cursor while a controller is connected in Minecraft, or add a timeout period to hide the cursor. It shows up every time a menu is opened, such as the Inventory for example.

**Comment by MrCrayfish** [comment]
For now you can unfocus your window (click somewhere else) and it won't pop up (assuming you are using the latest version of the mod)

**Comment by MrCrayfish** [comment]
A new update is dropping soon which will resolve this issue. The cursor will stay hidden even after opening your inventory, and will only appear if you actually move your mouse.
