### ISSUE TITLE
Controller testing/implementation and suggestions.

### ISSUE THREAD

**Issue by Slayer5934** [MrCrayfish/Controllable#17]
Let me know how I can help, I have some minor experience developing mods such as chococraft.

Suggestion/s:
- Add an onscreen keyboard which can be brought up with a button.
- Add the ability to de-select a controller, that way your not forced to choose one.

Controllers tested so far:
- PS4 controller - Works perfectly
- XBox360 controller - Works great except no deadzone
- Logitech F310 controller - Works great, some deadzone as in it mostly doesn't stray.
- Switch controller - Works great, some deadzone as in it mostly doesn't stray.

**Comment by MrCrayfish** [comment]
Closing due to clean up.
