### ISSUE TITLE
Have mod automatically disable when installed on server

### ISSUE THREAD

**Issue by CryoByte33** [MrCrayfish/Controllable#170]
Hey, love the mod! It lets me play without breaking my wrists more on a keyboard for hours 😄 

I would love to use this on on my small modpack for my server, but if I install it on the server, it crashes. Normally I'd have no issue just removing it but it causes the multiplayer menu to show a large red X for differing mod lists and I keep getting questions about it and it dissuades players from joining.

I'd love if it acted more like ToastControl or something else that is clientside only, but just doesn't do anything on the server instead of crashing it.

Thank you!

**Comment by vtenfys** [comment]
I spotted this commit in Mouse Tweaks mod which prevents the compatibility warning when only present on the client: https://github.com/YaLTeR/MouseTweaks/commit/d0eb6c5fa98ade90277f8f1225c9497306152fd0

Presumably the same line could be added to Controllable?

**Comment by MrCrayfish** [comment]
I've fixed this in an upcoming update
https://github.com/MrCrayfish/Controllable/commit/bbf33d3d351e66e330676df0df1f3013f2377134

**Comment by MrCrayfish** [comment]
My bad, this is an entirely different issue. I am assuming joining a Forge server with Controllable rejects the client?
