### ISSUE TITLE
Alternative "exiting" button

### ISSUE THREAD

**Issue by 2009XboxLiveKid** [MrCrayfish/Controllable#173]
Personally I am trying to make my playthrough as much alike as Minecraft: Legacy Edition, could you make it so that you no longer have to press the same button to exit the interface your in, rather making it so that you can press "B" or "O" on the controller to exit an interface

Alson on 0.11.0 on 1.16.3

**Comment by MrCrayfish** [comment]
A separate binding has been added in recent versions of Controllable to close inventories, etc.
