### ISSUE TITLE
Control hints overlap subtitles

### ISSUE THREAD

**Issue by vtenfys** [MrCrayfish/Controllable#179]
When subtitles are enabled in the *Music & Sound* menu or the *Accessibility Settings* menu, the control hints displayed by *Controllable* slightly overlap the subtitles. This can be seen in the following screenshot:

![Subtitles in the bottom right of Minecraft overlapped by control hints](https://user-images.githubusercontent.com/4248177/114402204-821b5e80-9b9b-11eb-89b1-d17ce2d6cde9.png)

I propose subtitles should be pushed upwards slightly by this mod when playing with a controller to compensate for the extra space taken up by control hints.

Note that when multiple subtitles appear on screen, they flow upwards rather than down, i.e. the bottom-most subtitle is always anchored to the same position; hopefully this means adjusting their position shouldn't be too complex.

I'm not yet familiar with Minecraft mod development however I'm currently at the beginning of a tutorial series for creating Forge mods, so I'm willing to write a PR once I'm familiar with the basics and if someone could point me to which part of the code should need updating :)

**Comment by MrCrayfish** [comment]
I believe I've fixed this issue in modern versions of Controllable. I recommend updating to 1.18.2 and above.
