### ISSUE TITLE
Problems with JEI on 12.2

### ISSUE THREAD

**Issue by PibePlayer** [MrCrayfish/Controllable#182]
I'm unable to click on any jei item to see it's recipe. Thanks for the great work being done!

**Comment by MrCrayfish** [comment]
A/X is not the button to show the recipe. You have to press B/Circle. (assuming you are using the latest version of the mod and 1.16.X)

**Comment by PibePlayer** [comment]
@MrCrayfish on the title itself I specified that I'm using 12.2.
I you don't want to do it since you have more pressing problems, please tell me what should I watch for and I'll give it a shot ;)

**Comment by MrCrayfish** [comment]
12.2?

**Comment by PibePlayer** [comment]
Yeah Minecraft 1.12.2, sorry

**Comment by MrCrayfish** [comment]
I am no longer supporting the 1.12.2 version of this mod. It was already a huge amount of time for the last update to backport the new features.

**Comment by PibePlayer** [comment]
I see, thanks anyways for your time.
Is there any tip or something to watch for if I want to tackle this issue by myself?

**Comment by mjdev83** [comment]
@PibePlayer did you find any fix ?
