### ISSUE TITLE
This server has enabled controller only stuck on screen

### ISSUE THREAD

**Issue by ImpSpy2** [MrCrayfish/Controllable#184]
When you do not have any controllers connected to your system, the message is stuck on the screen while in the world even if restrictToController is set to false in the server config.

**Comment by Tsoccerguy3** [comment]
![2021-04-17_00 12 52](https://user-images.githubusercontent.com/22108822/115101557-3b1ec780-9f13-11eb-9677-feefcfd2ca14.png)

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/ec5a62aeafa3bb445f7874a159b3d3370caac886
