### ISSUE TITLE
Player moves at slowest speed when flying

### ISSUE THREAD

**Issue by DragarX** [MrCrayfish/Controllable#185]
using the latest 0.12.0 on 1.16.5 when a player is flying they move at the same speed as the lowest movement speed when walking with the analog stick.

**Comment by MrCrayfish** [comment]
I can't seem to replicate the issue. Did this work fine in previous versions on 1.16.5?

**Comment by MrCrayfish** [comment]
Closing due to stale issue. If still an issue, feel free to open a new issue.
