### ISSUE TITLE
(Improvement) Higher Rotation Speed limit/sensitivity options

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#187]
I use a steam controller with "Mouse Like Joystick" for controllable, and at the max sensitivity, it still takes a little time to turn around completely,with the way steam input works, i can do anything to make the sensitivity the way i want it, except increase the maximum turn rate. with this increased more, we'd have access to faster turning, but at the same time because of how steam input works, finer smaller movements too.

**Comment by MrCrayfish** [comment]
I've increased the max sensitivity. It can now go up to 100 instead of 50

**Comment by dude98** [comment]
the sensitivity isn't able to be increased past 50 still in the latest.

**Comment by MrCrayfish** [comment]
I found the issue. I will have a patch soon
