### ISSUE TITLE
Nintendo Controller Icons and A/B, X/Y swap

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#188]
It'd be nice to have a proper nintendo switch icon set, as well as in the options menu to flip A/B for menu and in-game, and flip X/Y for menu and in-game, to allow the inventory button's icon to be correct, as well as jump being A without making a custom texture, since some people use switch controllers for this mod.

**Comment by MrCrayfish** [comment]
It doesn't need to be flipped. I just have to switch A/B and X/Y in the textures.

**Comment by NexusTheBrony** [comment]
I don't know when it changed, but A the button is being mapped to B the icon again. ofc in reference to the Switch controller

**Comment by dude98** [comment]
are you using steam or anything that emulates an xbox controller? if you are you might have the buttons set to follow by icon and not position, as the textures are based on position of the buttons (B is on the bottom which is Xbox's A Button, and X is on the top which is Xbox's Y Button)
easiest fix is flip them in the program you're using.
if you're using the switch controller natively, you used to be able to access an in game button rebinder and flip them, but idk if it was removed as i don't have minecraft open at the moment. if it is still there, you want the red button as switch's A, the green as switch's B, yellow is X, and blue is Y, that should have the proper button setup.
only other possibility is that the textures were flipped in the files, but i just looked at the buttons png in the github and they're still the same as before.

**Comment by NexusTheBrony** [comment]
> are you using steam or anything that emulates an xbox controller? if you are you might have the buttons set to follow by icon and not position, as the textures are based on position of the buttons (B is on the bottom which is Xbox's A Button, and X is on the top which is Xbox's Y Button) easiest fix is flip them in the program you're using. if you're using the switch controller natively, you used to be able to access an in game button rebinder and flip them, but idk if it was removed as i don't have minecraft open at the moment. if it is still there, you want the red button as switch's A, the green as switch's B, yellow is X, and blue is Y, that should have the proper button setup. only other possibility is that the textures were flipped in the files, but i just looked at the buttons png in the github and they're still the same as before.

actually, when I use it thru steam it does correctly, but it's labeled as an xbox controller which imo is kinda cheating. native use is where the issue properly arises
