### ISSUE TITLE
Flip Inventory Close and Quick Move

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#189]
The Buttons for Close Inventory and Quick Move in comparison to legacy and bedrock are flipped. it'd make sense to allow you to flip them back to closer match layouts.

**Comment by MrCrayfish** [comment]
The bindings for left click, right click, and quick move are now exposed in the next release. I don't know if I'll add a seperate button for closing inventory though

**Comment by dude98** [comment]
Me and a couple people i know have accidentally quick moved an item while trying to close our inventories before, as well as accidentally closing the inventory when trying to move something into our hotbar. it's mainly muscle memory, but that's the underlying issue with having close inventory not be the "back out of menu"(B or Circle) button.
