### ISSUE TITLE
More Icon Sets

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#191]
The three icon sets are nice, but they feel kinda limited. It'd be nice to have more sets like:
-Nintendo Switch (Current Default Looks Like Mix Of Switch And Xbox Or Android Controller)
-Xbox One (Current Xbox Icon Set Is 360)
-PS3 (Select And Start Instead Of Options And Touchpad)
-Steam Controller (More Of A Personal Preference)

**Comment by dude98** [comment]
also, maybe a gamecube controller icon set for the fun of it too? it has enough buttons.

**Comment by incogg** [comment]
![switch](https://user-images.githubusercontent.com/19463501/115989668-c4648700-a602-11eb-8f5b-b714a772ee49.png)
proposed change for the switch icons

**Comment by dude98** [comment]
I'd give the plus and minus a circular button, just like the rest, since it makes more sense for pro controllers.

**Comment by dude98** [comment]
I made the icon sets as best as i could, and even made the gamecube icon set for the fun of it, only things i had trouble with were the guide buttons for xbox one and steam, the ps3 start button, the left touchpad as a dpad for steam controller, and that's about it.
Edit: the triggers for the xbox one set need another look, they don't look great as just a recolour. and gamecube icons are gonna be weird just because the letters are just darker colours of the buttons. adjusted some things as well as added a set for nintendo switch gamecube style controllers
![buttons](https://user-images.githubusercontent.com/13279963/116005018-a172ac80-a5db-11eb-9ba8-7d907a9130ea.png)

**Comment by MrCrayfish** [comment]
Are you able to provide a list of the icon set names in order of the graphic?

**Comment by dude98** [comment]
List from top is:
-Default
-PS4
-Xbox 360
-Xbox One
-Nintendo Switch
-PS3
-Steam Controller
-Gamecube
-NS GCN Style (Nintendo Switch Gamecube Style)
I'm Making a New Nintendo 3ds icon set right now, using the controls from 3ds controller plus vigem (https://github.com/Eveldee/Eveldee.3DSCPlusViGEm) since it has a nice template for controls (one of the configs sets thumbstick click to left and right on the touchscreen with guide in the middle)

**Comment by dude98** [comment]
3DS icons added (At the end, Touchscreen Left and Touchscreen Right icons added
(deleted set, use edited one)
Edit: Fixed RT and LT for Xbox One Set and Made 3ds ZL and ZR look more round
![buttons](https://user-images.githubusercontent.com/13279963/116010686-df30fe80-a5f6-11eb-9bcc-f351abe8c66a.png)

**Comment by dude98** [comment]
one possible issue with any of these icon sets are wrong position on the nintendo ones, would be best fixed with a "Flip A and B" and "Flip X and Y" option.

**Comment by MrCrayfish** [comment]
I am most likely not going to include the Gamecube controller since it's missing buttons. If anyone has the controller, does it actually work?

**Comment by MrCrayfish** [comment]
Also the 3DS is a little too niche to include officially, maybe in the future I can add support to add custom icons.

**Comment by MrCrayfish** [comment]
I released new sets in 0.13.0

**Comment by dude98** [comment]
i used a gamecube controller with minecraft for switch, it works but only barely (change the inputs a fair bit)
