### ISSUE TITLE
Game crashes when launched with controller connected

### ISSUE THREAD

**Issue by Luiswagula** [MrCrayfish/Controllable#199]
Specifically a ps4 DualShock and a wired hori ps4 controller. After the game loads up while either of these controllers is already plugged in it crashes.

**Comment by MrCrayfish** [comment]
Can you please send the crash report?

**Comment by Gilyel** [comment]
I have the same issue, here is the crash file:
[crash-2021-05-14_00.28.43-fml.txt](https://github.com/MrCrayfish/Controllable/files/6476443/crash-2021-05-14_00.28.43-fml.txt)

**Comment by MrCrayfish** [comment]
I've made a potential fix. Can you try this version of the mod? https://www.dropbox.com/s/e5bxb95ov15t1lk/controllable-0.13.2-1.16.3.jar?dl=0

**Comment by Gilyel** [comment]
Ok.

**Comment by Gilyel** [comment]
Worked! Thank you!

**Comment by MrCrayfish** [comment]
Fixed in 36414d16294b44c32205023c990369faabca4c99
