### ISSUE TITLE
Cant dismount minecarts/boats/horses using xbox 360 controller

### ISSUE THREAD

**Issue by complicitsalami** [MrCrayfish/Controllable#202]
Tested with xbox one controller and elite controller and they work fine to dismount. Only older 360 wireless controllers that get stuck in boats/minecarts and any mounts.

**Comment by MrCrayfish** [comment]
Dismounting is controlled by sneaking. Can you sneak on your 360 controller? I'd check on https://gamepad-tester.com/ if it's not a broken thumbstick. Otherwise you can try binding sneak to a different button.
