### ISSUE TITLE
Controller Won't Show Up When Connected-Also Tested on gamepad tester

### ISSUE THREAD

**Issue by LUFCRyan** [MrCrayfish/Controllable#208]
When my Xbox controller is connected with bluetooth and I go to select it in the mod nothing appears to be selected
available to select

on MacOS 11.4
Controllable 0.13.3

**Comment by artus25200** [comment]
Same

**Comment by MrCrayfish** [comment]
Check out the documentation on different methods of connecting your controller to see if something else works.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
