### ISSUE TITLE
Dropping not Working

### ISSUE THREAD

**Issue by SondiGER** [MrCrayfish/Controllable#209]
for some Reason i cant Drop items. Whatever Button i put Dropping on doesnt want to work.
i dont know if its my Controller (8BITDO SF30 PRO GAMEPAD) that i use Via a USB Cabel, or the Game just dont Wanting me to do it but i dont know lets see how it turns out.

**Comment by Meek97** [comment]
I ran into this issue myself, and while trying to search for a solution I found this issue report. I found a solution to my problem. I had also installed the [ItemPhysics Full](https://www.curseforge.com/minecraft/mc-mods/itemphysic) mod. That mod was causing the problem for me. 
In an instance with nothing but minecraft, forge, and controllable installed the mod worked as intended. If I simply added the ItemPhysics Full mod, that is when item dropping would stop working.

I would suggest checking your mod pack for any mods that change item dropping behavior and disabling them to see if this is the problem for you as well.

**Comment by MilkmanG** [comment]
> I ran into this issue myself, and while trying to search for a solution I found this issue report. I found a solution to my problem. I had also installed the [ItemPhysics Full](https://www.curseforge.com/minecraft/mc-mods/itemphysic) mod. That mod was causing the problem for me. In an instance with nothing but minecraft, forge, and controllable installed the mod worked as intended. If I simply added the ItemPhysics Full mod, that is when item dropping would stop working.
> 
> I would suggest checking your mod pack for any mods that change item dropping behavior and disabling them to see if this is the problem for you as well.


Guys I appreciate the info on this matter, I don't usually comment anywhere but here's what I found, in case you like the ItemPhysics Full mod, which I personally love, the issues with these mods is a specific setting which is the custom throw. On that note if you disable the custom throw setting in these two files in the config folder (itemphysic.json and itemphysic.cfg ) by setting it to false you will be able to throw items normally. That's if you're playing on 1.12.2, I haven't tried for other versions.

Hope this helps.
