### ISSUE TITLE
Controllable doesn't recognize Joy-Cons despite being recognized by gamepad-tester

### ISSUE THREAD

**Issue by ajsirota** [MrCrayfish/Controllable#210]
I don't see my Nintendo Switch Joy-Cons in the Controllable menu despite the gamepad-tester.com site recognizing them.

* Minecraft 1.16.3 launched with MultiMC
* Forge 34.1.0
* Controllable 0.13.3
* macOS 11.3 on Intel

Any help would be much appreciated. Thank you!

**Comment by artus25200** [comment]
Is controllable supposed to support joy con ?

**Comment by kurisubrooks** [comment]
Also having this issue with my Switch Pro Controller. Correctly works in gamepad-tester.com.
- Minecraft 1.18.1 (M1 / ARM, running natively through MultiMC)
- Forge 39.0.5
- Controllable 0.15.1
- macOS 12.0.1 (M1 Pro)

**Comment by MrCrayfish** [comment]
I've written some guides on different methods of connecting controllers for Controllable. I've had reports that the Linux method (Steam Virtual Gamepad) works on macOS, which means you can use Joycons with Controllable.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad
