### ISSUE TITLE
Not working when window is not in focus

### ISSUE THREAD

**Issue by Gavin456b** [MrCrayfish/Controllable#211]
So I use this mod to play with two instances of the game running on LAN, with dual monitors and two seperate controllers, everything works well but whenever I click off one instance the game goes to the pause screen and if I try to unpause it just immediately pauses again as if the escape buttom is constantly being held. It will not stop until I click back onto the window. Which then the problem happens on the opposite screen when I click off of that one.

**Comment by MrCrayfish** [comment]
Press F3 + P
