### ISSUE TITLE
Request for feature

### ISSUE THREAD

**Issue by Gavin456b** [MrCrayfish/Controllable#212]
Request to make open & close inventory separate bindings

**Comment by CaptClockobob** [comment]
The impulse to just press b to close the inventory is too strong.

**Comment by Gavin456b** [comment]
> The impulse to just press b to close the inventory is too strong.

Execpt b isn't to close inventory. The binding for inventory is set to Y by default so I have to hit Y to open and Y to close. Which mean shift click to fast move items has to be bound to B. Which is super annoying

**Comment by CaptClockobob** [comment]
That's exactly my point. B is the most common "back" button. Not being able to use it in infuriating.

**Comment by MagnusCanDraw** [comment]
@MrCrayfish please fix this. this is what keeps the mod from reaching a level of perfection

**Comment by Wh1rledPeas** [comment]
> Request to make open & close inventory separate bindings

I have to agree here.  I've played on XBOX for the past 5+ years.  **(Y)** opens the inventory, but once opened, **(Y)** becomes the Quick Move button and **(B)** closes inventory.

On the XBOX platform, **(B)** is *almost always* the "back button", no matter what game/screen you're on.  It has trained my brain that way and after playing on PC/Java, with the Controllable mod, for the past 6 months, I still have to fight the urge to use **(B)** to back out of the inventory.

Issue #173 is a request for this same functionality.

**Comment by MrCrayfish** [comment]
This has been added in recent versions of Controllable
