### ISSUE TITLE
[linux] no gamepads detected on current releases

### ISSUE THREAD

**Issue by kkmaslowski** [MrCrayfish/Controllable#221]
Hi.
Last working version: 0.9.1 (pre GLFW). 
All next releases are not detecting my gamepads (usb connected) under linux. Tested: 0.11.2, 0.12.0, 0.13.0, 0.13.3.

Details:
Fedora 35
Minecraft 1.16.5 + cystal launcher.

**Comment by kkmaslowski** [comment]
Update: all new versions detect my XBox 360 wireless controllers, but not detecting no-name usb gamepads (hama - urage).

**Comment by MrCrayfish** [comment]
I've written a guide on connect a controller with Linux, while plugging it in may work for some controllers, it may not work with others. Controllable does not provide special drivers to make controllers work, that is up to the user. However you can follow this guide for Linux: https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
