### ISSUE TITLE
Crash due to duplicate key binding

### ISSUE THREAD

**Issue by FocusPunch** [MrCrayfish/Controllable#223]
## Current Behavior
Game crashes on load, citing a duplicate key as the error when another mod registers a keybind twice.

## Steps to Reproduce

1. Install Controllable and [Spice of Life: Potato Edition](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-potato-edition)
2. Open Minecraft.
3. In the options menu, open the Controllable settings, choose a controller and click "Bindings".
4. Close Minecraft.
5. Launch again and it will crash.

## Context (Environment)
Minecraft Version: 1.16.5
Forge Version: 36.2.2
Controllable Version: 0.13.3
Spice of Life: Potato Edition Version: 1.1.0
Controller: Playstation 4 (DS4)

## Detailed Description
The file "config\controllable\key_adapters.properties" is created when navigating to the "Binding" menu. Deleting the file will allow the game to open again.

Although this seems like the other mod is at fault it would be nice to be able to handle the error.

## Crash Log
Error Message:
   "Duplicate key net.minecraft.client.settings.KeyBinding@3e53c4ad"

[crash-2021-08-08_17.08.41-client.txt](https://github.com/MrCrayfish/Controllable/files/6951520/crash-2021-08-08_17.08.41-client.txt)

Thanks for the awesome mods and any help!

**Comment by MrCrayfish** [comment]
This should be fixed now!
