### ISSUE TITLE
Support 1.17.X

### ISSUE THREAD

**Issue by NSExceptional** [MrCrayfish/Controllable#224]
Pls

**Comment by NSExceptional** [comment]
Lol why did you close this without any reply, @MrCrayfish?

**Comment by MrCrayfish** [comment]
Because it's spam. Do you really think mod developers don't think of updating? It's literally the most obvious thing to do when a new version is available. It's very annoying for not only myself but every other developer.

**Comment by NSExceptional** [comment]
I checked to see if you had a 1.17 branch before I opened this issue so I assumed you weren't working on it since there isn't one. I'm a developer too and you're being kinda brash here, but sorry.

**Comment by NSExceptional** [comment]
Even if it is annoying, I wouldn't ever close an issue without saying anything unless the issue was empty.

What if someone else sees my closed issue and opens a duplicate because you didn't say why you closed it?

**Comment by MrCrayfish** [comment]
You typed "Pls" what else is there more to say?

**Comment by MrCrayfish** [comment]
This mod would be updated if I could. Mixins don't exist in Forge 1.17.1 so I can't really start development.

**Comment by NSExceptional** [comment]
↑ that's all you had to say, friend. Part of the job we have as developers is to deal with people outside our "circle of knowledge", but I'm still sorry if my issue was annoying.

It can be frustrating when someone opens an issue on something that is obvious to you, but try to remember: it may not be obvious to them. I'm an iOS developer so the Minecraft mod scene is not something I'm super familiar with. 

Now that you've told me why there are probably *no* forge mods for 1.17 specifically yet, I won't go around opening issues like this on other repos. So, thank you 🤟🏻

**Comment by MrCrayfish** [comment]
Please don't tell me how to be a professional developer when clearly this wasn't shown in the first place with the message "Pls". All I am saying is to type a sentence or two then I wouldn't have closed without context and we wouldn't be here.
