### ISSUE TITLE
Crash with 1.12.2

### ISSUE THREAD

**Issue by KorewaLidesu** [MrCrayfish/Controllable#225]
Hope you still support on this version, crash happen with 0.11.2
[Log here](https://gist.github.com/KorewaLidesu/35a89153052dc8f182788bb1116e6eb8)

Seem like Mixin incompatibility

**Comment by Etaash-mathamsetty** [comment]
Have you tried running the mod alone without all of the other mods?

**Comment by wayneaking95** [comment]
Crashed wile opening it up in 1.12.2

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Controllable (controllable)
Exit Code: -1

**Comment by XXBLD1029** [comment]
> 

The same thing happend with me so I started using 1.18.2, but my switch pro controller won't do anything even though it says it's connected

**Comment by MrCrayfish** [comment]
Closing this issue as I no longer maintain the 1.12.2 version of this mod
