### ISSUE TITLE
Crash on start [1.14.4]

### ISSUE THREAD

**Issue by SalviaUnga** [MrCrayfish/Controllable#23]
Well, I've tried to run this mod on 1.14.4, but it is crashing my Minecraft at load. I tried to delete all mods except this, but still nothing. Is there are an way to fix this?

**Comment by SalviaUnga** [comment]
[crash-2019-09-14_23.33.48-client.txt](https://github.com/MrCrayfish/Controllable/files/3612979/crash-2019-09-14_23.33.48-client.txt)

**Comment by MrCrayfish** [comment]
Fixed in 0.5.0
