### ISSUE TITLE
16 button controller

### ISSUE THREAD

**Issue by Voajus** [MrCrayfish/Controllable#230]
Hello I play on mostly 1.12.2, My main pc controller is a sanwa 16 button gamepad. Is it possible for you to make it compatible? Your mod reads it fine but it partially confirms all the buttons.

**Comment by MrCrayfish** [comment]
Controllable doesn't actually make controllers compatible. Support is determined by GLFW, the underlying graphics/input library that Minecraft uses. You'll have to fork this mod and use an alternate library if you want to support a niche controller.
