### ISSUE TITLE
Duplicate keys, enigmatica 6

### ISSUE THREAD

**Issue by kyuMomo** [MrCrayfish/Controllable#233]
was hoping this would work with enigmatica 6, but it doesn't when I switch the controls to my preferences. This mod also won't let me remove the controller keybinds that I don't like. 

[crash-2021-10-15_21.58.55-client.txt](https://github.com/MrCrayfish/Controllable/files/7356586/crash-2021-10-15_21.58.55-client.txt)

another log
[crash-2021-10-17_11.59.48-client.txt](https://github.com/MrCrayfish/Controllable/files/7360373/crash-2021-10-17_11.59.48-client.txt)
:

**Comment by MrCrayfish** [comment]
Keybinds can be reset by deleting the bindings found in the config folder. I'll look into the issue though.

**Comment by kyuMomo** [comment]
Oh, thank you! I didn't even think of that. O:

yeah, I have no idea why customizing the keybinds makes it crash on the next start up. To be able to actually boot enigmatica, I have to delete the controllable config files each time and then re-change them in-game.

**Comment by kyuMomo** [comment]
[crash-2021-11-01_08.52.24-client.txt](https://github.com/MrCrayfish/Controllable/files/7462728/crash-2021-11-01_08.52.24-client.txt)

[crash-2021-11-02_08.22.36-client.txt](https://github.com/MrCrayfish/Controllable/files/7462729/crash-2021-11-02_08.22.36-client.txt)



Some more crash logs
