### ISSUE TITLE
No controller option

### ISSUE THREAD

**Issue by StarPAnims** [MrCrayfish/Controllable#236]
I have it installed, on the most recent version, i'm using fabric, and tried to use it with forge too, not working at all!
![image](https://user-images.githubusercontent.com/88120204/139560675-5c185fe7-25cb-4c94-8bc7-245b63da9956.png)

I've used it before in other versions, it worked, now in this new one, nothing, none of forge and fabric 1.17 works

**Comment by MrCrayfish** [comment]
It's a Forge mod, not Fabric
