### ISSUE TITLE
Controllable 1.17 Virtual Mouse Bugged

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#238]
when virtual mouse is enabled, hovering over buttons with the virtual mouse doesn't light the buttons up, and when in inventory, the item you pickup doesn't show up at the cursor.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/cd14f4e0d0b1e9174f24b0c7266759910cc19a3a
