### ISSUE TITLE
[1.12.2][Forge 14.23.5][Controllable 0.11.2][MultiMC Launcher][Enigmatica 2] Controller not appearing in "select controller" list

### ISSUE THREAD

**Issue by AzazelWormwood** [MrCrayfish/Controllable#239]
I'm using a wired connection Xbox One controller, a Razer Wolverine. The controller itself works as I've previously had it configured through Steam, but I have been unable to see it in the select controller list for this mod. Disabling Steam controller support did not solve the issue. Let me know if you need any more information from me to help! I will attach a list of mods below. Thanks!

    AppleCore (by squeek502)
    Just Enough Resources (JER) (by way2muchnoise)
    Just Enough Energistics (JEE) (by TheRealp455w0rd)
    Better Builder's Wands (by Portablejim)
    PneumaticCraft: Repressurized (by desht_08)
    Hwyla (by TehNut)
    Schematica (by Lunatrius)
    Bad Wither No Cookie - Reloaded (by Kreezxil)
    Demagnetize (by comp500)
    Thermal Cultivation (by TeamCoFH)
    LunatriusCore (by Lunatrius)
    Just Enough HarvestCraft (JEHC) (by mrapplexz)
    In Control! (by McJty)
    Cosmetic Armor Reworked (by LainMI)
    Gendustry JEI Addon (by ninjabrain1)
    Colytra (Forge) (by TheIllusiveC4)
    Shadowfacts' Forgelin (by ShadowfactsDev)
    LibrarianLib (by wiresegal)
    Actually Additions (by Ellpeck)
    Wireless Crafting Terminal (by TheRealp455w0rd)
    Magic Bees (by MysteriousAges)
    Natura (by mDiyo)
    NotEnoughIDs (by fewizz_)
    Tesla Core Lib (by face_of_cat)
    ZeroCore 2 (by ZeroNoRyouki)
    JEI Villagers (by Buuz135)
    No Night Vision Flashing (by TeamCoFH)
    Botania (by Vazkii)
    Reborn Core (by modmuss50)
    IvToolkit (by Ivorforce)
    More Overlays (by FeldiM245)
    YNot (by asiekierka)
    No Mob Spawning on Trees (by oldjunyi)
    Thermal Foundation (by TeamCoFH)
    ShadowMC (by ShadowfactsDev)
    Mekanism (by bradyaidanc)
    Redstone Flux (by TeamCoFH)
    Mekanism Generators (by bradyaidanc)
    Mekanism Tools (by bradyaidanc)
    CoFH Core (by TeamCoFH)
    Ender Storage 1.8.+ (by covers1624)
    Thermal Expansion (by TeamCoFH)
    ToroHealth Damage Indicators (by ToroCraft)
    PlayersDropHeads (by josephcsible)
    Backpacks (by Eydamos)
    Fence Jumper (by TheRealp455w0rd)
    MeeCreeps (by McJty)
    Dirt2Path [FORGE] (by mallrat208)
    NuclearCraft (by tomdodd4598)
    RFTools Control (by McJty)
    Just Enough Throwing In Fluids (JETIF) (by Lykrast)
    Ding (by ohaiiChun)
    FPS Reducer (by bre2el)
    CoFH World (by TeamCoFH)
    p455w0rd's Library (by TheRealp455w0rd)
    TESLA (by DarkhaxDev)
    Just Enough Pattern Banners (by Lorexe)
    Placebo (by Shadows_of_Fire)
    Ancient Warfare 2 (by Shadowmage4513)
    JAOPCA (by TheLMiffy1111)
    Farming for Blockheads (by BlayTheNinth)
    Super Sound Muffler: Revived (by Firstnecron)
    Integrated Dynamics (by kroeser)
    /dank/null (by TheRealp455w0rd)
    Better Advancements (by way2muchnoise)
    Immersive Technology (by tgstyle0)
    Forestry (by _ForgeUser7678633)
    Bookshelf (by DarkhaxDev)
    EnderCore (by tterrag1098)
    KleeSlabs (by BlayTheNinth)
    CC: Tweaked (by SquidDev)
    Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth)
    WanionLib (by WanionCane)
    AE2 Stuff (by bdew)
    GunpowderLib (by Jackyy)
    Binnie's Mods (by _ForgeUser9116757)
    RFTools (by McJty)
    Pam's HarvestCraft (by pamharvestcraft)
    Integrated Tunnels (by kroeser)
    Extreme Reactors (by ZeroNoRyouki)
    Thermal Dynamics (by TeamCoFH)
    Building Gadgets (by Direwolf20)
    AI Improvements (by QueenOfMissiles)
    Flat Colored Blocks (by AlgorithmX2)
    FTB Backups (Forge) (by FTB)
    Tips (by DarkhaxDev)
    Modular Routers (by desht_08)
    Morph-o-Tool (by Vazkii)
    Phosphor (Forge) (by jellysquid3)
    Draconic Evolution (by brandon3055)
    OpenComputers (by Sangar_)
    Wizardry Mod (by Demoniaque1)
    BiblioCraft (by Nuchaz)
    Carry On (by Tschipp)
    Farseek (by delvr)
    Armor Toughness Bar (by tfarecnim)
    Chisel (by tterrag1098)
    Brandon's Core (by brandon3055)
    Spice of Life: Carrot Edition (by lordcazsius)
    CraftStudio API (by ZeAmateis)
    Grass Burner (by not_loki)
    Project Intelligence (by brandon3055)
    MysticalLib (by Noobanidus)
    XNet (by McJty)
    Immersive Engineering (by BluSunrize)
    Wawla - What Are We Looking At (by DarkhaxDev)
    ConnectedTexturesMod (by tterrag1098)
    CraftTweaker (by Jaredlll08)
    ArchitectureCraft - TridentMC Version (by darkevilmac)
    Ore Excavation (by Funwayguy)
    Quick Leaf Decay (by Lumien231)
    Common Capabilities (by kroeser)
    Custom Main Menu (by Lumien231)
    Advanced Generators (by bdew)
    Quark (by Vazkii)
    Industrial Foregoing (by Buuz135)
    AutoRegLib (by Vazkii)
    Construct's Armory (by TheIllusiveC4)
    Thaumcraft (by Azanor13)
    Villager Market (by face_of_cat)
    Torchmaster (by xalcon)
    Funky Locomotion (by Forge_User_06804776)
    McJtyLib (by McJty)
    Streams (by delvr)
    Mantle (by mDiyo)
    ExtraCells2 (by Forge_User_54797008)
    UniDict (by WanionCane)
    Inventory Tweaks [1.12 only] (by JimeoWan)
    Biomes O' Plenty (by Forstride)
    Compact Machines (by davenonymous)
    Controlling (by Jaredlll08)
    Resource Loader (by Lumien231)
    Tinkers' Tool Leveling (by bonusboni)
    Thaumic JEI (by Buuz135)
    Gendustry (by bdew)
    BdLib (by bdew)
    Garden Stuff (by Texelsaur)
    Blood Magic (by WayofTime)
    Environmental Materials (by ValkyrieofNight)
    RFTools Dimensions (by McJty)
    Cooking for Blockheads (by BlayTheNinth)
    MTLib (by Jaredlll08)
    Immersive Petroleum (by Flaxbeard)
    Cyclic (by Lothrazar)
    SwingThroughGrass (by exidex)
    Extra Bit Manipulation (by Phylogeny)
    Custom Backgrounds (by Lumien231)
    Industrial Craft (by sfPlayer1)
    DiscordSuite (by hrznstudio)
    Iron Backpacks (by gr8pefish)
    Recurrent Complex (by Ivorforce)
    Extra Rails (by ShadowfactsDev)
    FastWorkbench (by Shadows_of_Fire)
    AppleSkin (by squeek502)
    Better Questing - Quest Book (by Drethic)
    xXx_MoreToolMats_xXx (a PlusTiC fork without the evil, and apparently some new bugs idk) (by TeamDman)
    ME Capability Adapter (by rfctksSparkle)
    Engineer's Doors (by nihiltres)
    Environmental Tech (by ValkyrieofNight)
    LibVulpes (by zmaster587)
    Advanced Rocketry (by zmaster587)
    FTB Utilities (Forge) (by FTB)
    ModTweaker (by Jaredlll08)
    Blockcraftery (by EpicSquid315)
    Just Enough Items (JEI) (by mezz)
    The Twilight Forest (by Benimatic)
    Baubles (by Azanor13)
    Iron Chests (by ProgWML6)
    Chunk-Pregenerator (by Speiger)
    BetterFps (by Guichaguri)
    ValkyrieLib (by ValkyrieofNight)
    Thaumic Tinkerer (by gaeakat)
    Overloaded Armor Bar (by tfarecnim)
    Just Enough Petroleum (by BordListian)
    Default Options (by BlayTheNinth)
    ReAuth (by TechnicianLP)
    Patchouli (by Vazkii)
    Thermal Innovation (by TeamCoFH)
    MineColonies (by H3lay)
    RandomPatches (Forge) (by TheRandomLabs)
    FastFurnace (by Shadows_of_Fire)
    Applied Energistics 2 (by AlgorithmX2)
    Diet Hoppers (by Forge_User_06804776)
    FTB Library (Forge) (Legacy) (by FTB)
    OpenModsLib (by OpenMods)
    OpenBlocks (by OpenMods)
    Redstone Arsenal (by TeamCoFH)
    Chameleon (by Texelsaur)
    Dark Utilities (by DarkhaxDev)
    AE2 Wireless Terminal Library (by TheRealp455w0rd)
    Better Questing (by Funwayguy)
    Better Questing - Standard Expansion (by Funwayguy)
    Guide-API (by TehNut)
    Pretty Beaches (by BlayTheNinth)
    Horse Tweaks (by BlayTheNinth)
    TipTheScales (by Jaredlll08)
    Tomb Many Graves 2 (by M4thG33k)
    MCMultiPart (by amadornes)
    Rustic (by cadaverous_queen)
    Toast Control (by Shadows_of_Fire)
    Akashic Tome (by Vazkii)
    Psi (by Vazkii)
    Loot Capacitor Tooltips (by tfarecnim)
    Cyclops Core (by kroeser)
    Unloader (by Unnoen)
    Mouse Tweaks (by YaLTeR)
    Storage Drawers (by Texelsaur)
    Chisels & Bits (by AlgorithmX2)
    Clumps (by Jaredlll08)
    Actually Baubles (by Jackyy)
    JEI Bees (by bdew)
    Career Bees (by Forge_User_06804776)
    Just Sleep (by modmuss50)
    OldJavaWarning (by DarkhaxDev)
    Animania Base (by Purplicious_Cow_)
    CodeChicken Lib 1.8.+ (by covers1624)
    Ender IO (by idontwantthisaccount4)
    JourneyMap (by techbrew)
    MemoryTester (by KaptainWutax)
    Just Enough Reactors (by BrainStone)
    Nature's Compass (by Chaosyr)
    Extra Utilities (by Forge_User_06804776)
    Neat (by Vazkii)
    MalisisDoors (by Ordinastie)
    PlaneFix (by Shadows_of_Fire)
    Scannable (by Sangar_)
    MalisisCore (by Ordinastie)
    Astral Sorcery (by HellFirePvP)
    Not Enough Wands (by romelo333)
    Mystical World (by Noobanidus)
    Roots (by Noobanidus)
    Tinkers Construct (by mDiyo)
    The Lost Cities (by McJty)
    Unlimited Chisel Works (by asiekierka)
    Foam​Fix (by asiekierka)
    WrapUp (by TheLMiffy1111)
    Integration Foregoing (by Jackyy)
    Embers Rekindled (by BordListian)

**Comment by MrCrayfish** [comment]
Closing since I no longer maintain the 1.12.2 version of this mod.
