### ISSUE TITLE
Port to Fabric for 1.14+

### ISSUE THREAD

**Issue by patchbank** [MrCrayfish/Controllable#24]
Hello!

Are there any plans to do a Fabric port / make this compatible with the Fabric modloader?

**Comment by MrCrayfish** [comment]
No

**Comment by patchbank** [comment]
May I ask why? Fabric is gaining a lot of well deserved popularity. There are more and more mods for it every day, even big ones like WorldEdit are doing a Fabric port.

I would like to hear the reason behind the decision against Fabric from someone who knows what he’s doing. 

Best regards!

**Comment by MrCrayfish** [comment]
It's a time issue. I have many projects that I am working on that are more important than porting this mod to Fabric and learning a whole new system. This mod heavy depends on ASM tranformations to replace vanilla code and porting that code to Mixins will take a while. Feel free to find someone who is experienced with Fabric to contact me and I can give them permission to port and release a version of Controllable for Fabric.
