### ISSUE TITLE
Newest update immediately crashes, MultiMC Launcher Enigmatica 6 modpack 1.16.5 forge 36.2.4

### ISSUE THREAD

**Issue by kyuMomo** [MrCrayfish/Controllable#240]
The 0.13.3 controllable jar still launches successfully, but the the newest controllable 0.14.0 for v1.16.5: immediately crashes whenever I try it.  I'm not sure what's going on or if I'm doing something wrong.

Using: forge 36.2.4

[crash 1.txt](https://github.com/MrCrayfish/Controllable/files/7494936/crash.1.txt)

**Comment by agentwolf88** [comment]
Same

0.14.0 for 1.16.5 crashs

https://paste.ee/p/zdkQc

**Comment by MrCrayfish** [comment]
Should be fixed in 0.14.1
