### ISSUE TITLE
Mod crashes at launch with latest MC Eternal modpack and latest Controllable version

### ISSUE THREAD

**Issue by sparioendernerd** [MrCrayfish/Controllable#241]
When using the latest MC Eternal modpack and the lastest version of Controllable for 1.12.2, version 0.11.2, the game crashes on launch. If I use an older version, 0.3.1, it will launch and work properly.

I've included the log's output.
[Minecraft Crash Log.txt](https://github.com/MrCrayfish/Controllable/files/7524007/Minecraft.Crash.Log.txt)

**Comment by MrCrayfish** [comment]
Closing since I no longer maintain the 1.12.2 version of this mod.
