### ISSUE TITLE
Support random third-party controllers with a community game controller DB via SDL_GameControllerDB

### ISSUE THREAD

**Issue by silbinarywolf** [MrCrayfish/Controllable#242]
Hey there!

I noticed that you are investigating the idea of community controller mappings to solve the issue of controllers such as the PS3 Controller not being easy to get "just working" with PC.

This is something I hit when shipping a game on Steam and in my travels when trying to solve this problem, I stumbled upon this:
https://github.com/gabomdq/SDL_GameControllerDB

It's a community-sourced database of various controller types wherein you can use the GUID of the controller to automatically detect an existing mapping.

Maybe you're already aware of this but if not, I hope this helps you out if you decide to try to tackle this in the future.

**Comment by MrCrayfish** [comment]
It's actually already in the mod https://github.com/MrCrayfish/Controllable/blob/1.17.X/src/main/resources/gamecontrollerdb.txt
