### ISSUE TITLE
Optifine + Conrtollable in 1.17.1 = invisible cursor in inventory menu

### ISSUE THREAD

**Issue by setzke** [MrCrayfish/Controllable#243]
Hey! I see this a couple times in old issues, but I am not sure how to fix. It happens when I have optifine installed... I removed optifine from my mod folder and things worked as expected; put it back and it messed up again. Here's my debug log from after I added optifine back:

https://pastebin.com/CUmA34a1

| Stuff | Version |
| --- | --- |
| Minecraft: | 1.17.1 |
| Controllable: | 0.14.0 |
| OptiFine: | HD U H1 |
| Java: | 16.0.1 |
| Forge: | 37.0.109 |

Any advice appreciated!

**Comment by setzke** [comment]
Hey, so turn off virtual controls, and it's good.  Obviously you're now in control of the real mouse so you can't split screen or something, but at least I can solo without issue and can quit researching optifine replacements.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/5f91e4ec6702c9e186fbdf69b15d850bc4aee267
