### ISSUE TITLE
Consider making two releases: one with GLFW mappings and one with the legacy mappings

### ISSUE THREAD

**Issue by DarthCaesium** [MrCrayfish/Controllable#244]
I am asking this because these mappings don't work for Xbox One and Xbox Series controllers on Linux, and also presumably on MacOS based on other issues submitted to the repo. I have tried using version 0.9.1, but this has a glitch that prevents any movement that requires holding down (as in not releasing straight away, so not quickly tapping), meaning that it is impossible to eat, run, or break blocks. If you don't want to commit to two releases, then at least please consider releasing at least one last version which does not have these glitches and uses the custom mappings.

**Comment by MrCrayfish** [comment]
I've written some guides on different methods of connecting your controller. If you're on Windows, I suggest checking out the GlosSI method, other if on macOS/Linux, try using the Steam Virtual Gamepad method (it has been reported to work on macOS too). https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
