### ISSUE TITLE
Journey Map Compatability

### ISSUE THREAD

**Issue by ashbob16478** [MrCrayfish/Controllable#249]
To start i'm loving this mod! I've inly used it for a day but i'm finally able to play modded minecraft with my brother (he doesn't have a pc :( )

I'm hacing issues getting the journey maps open fullscreen map function to work with a Duelshock 4 controller. I've tried both the "share" button and up on the d-pad and none of them seem to do anything at all. Although not a massive issue for a skyblock pack, which is what we're currently playing, it becomes an issue in regular worlds as its impossible to create waypoint or even just to see a bigger map.

Thanks in advance!

**Comment by MrCrayfish** [comment]
Unfortunately Controllable will never be 100% compatible with every mod. I'd love to see how Journey Map opens the map but it's closed source. I may be able to fix the issue though. I'll keep this open.

**Comment by ashbob16478** [comment]
Thanks for looking into it and keeping the thread open whilst you do! When i sow Journey map is closed source i thought that would be it!

**Comment by MrCrayfish** [comment]
Unfortunately not going to support the mod since it hinders on MC updates, JEI is already an issue.
