### ISSUE TITLE
Minor issues with (my) Xbox One Controller

### ISSUE THREAD

**Issue by TemporalDriver** [MrCrayfish/Controllable#25]
I only say "my" controller since I can't really be sure if anyone else is having this issue.

But I'm running 1.14.4, with the newest version of Controllable (0.5.0), and the recommended version of Forge (28.1.0), and connecting through Windows 10's bluetooth, not directly through USB or the official Xbox adapter.

Functionality-wise, the mod is mostly working perfect for me, aside from one thing I've noticed. Whenever I'm swapping to the left or right in my hotbar, my RB and LB buttons to the opposite (right goes left, left goes right)

The only other issue I've noticed so far is the on-screen button guide. I'm only getting button guides for a Dualshock controller, not an Xbox One controller. 

That last issue, I'm not even completely sure it's an issue, I didn't notice a screenshot with Xbox One mappings, so I'm not even sure if they're implemented yet. If they aren't and the PS4 indicators are all that's there at this point, disregard that last issue.

Finally, I'm sorry if this issue post comes off as a mess. This is my first time reporting an issue on GitHub, so I'm not really sure what the general etiquette is for issues/info. If there's any more info you need on my Minecraft or PC, I'm glad to provide it.

**Comment by MrCrayfish** [comment]
Fixed bumper buttons in 0.5.1
Button graphics for Xbox are coming soon. It's not a bug.
