### ISSUE TITLE
Crash using Controllable 0.15.1 with MC 1.18

### ISSUE THREAD

**Issue by TechnoDarkOne** [MrCrayfish/Controllable#250]
Attached crash lo
[crash-2021-12-03_08.55.38-client.txt](https://github.com/MrCrayfish/Controllable/files/7651814/crash-2021-12-03_08.55.38-client.txt)
g.

**Comment by MrCrayfish** [comment]
1.18 is no longer a supported version of this mod, please use 1.18.2 or higher.
