### ISSUE TITLE
Xbox Controller will not pop up on Mac OS

### ISSUE THREAD

**Issue by mintaliciouss** [MrCrayfish/Controllable#251]
Been trying to get multiple controllers on MacOS to pop up on Controllable but none of them work regardless of connection type, USB and Bluetooth. Any ideas or some sort of setting on Mac that I'm supposed to approve for it be discoverable on Controllable?

**Comment by MrCrayfish** [comment]
I've written some guides on connecting a controller. I've had reports that the Linux method (Steam Virtual Gamepad) works on macOS, which means you should be able to use the Xbox controller.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
