### ISSUE TITLE
Ps4 controller 

### ISSUE THREAD

**Issue by Willll447** [MrCrayfish/Controllable#253]
When I tried to use the pa 4 controller it won't work wirless Could you add a wirles fearture plz

**Comment by PokeyManatee4** [comment]
It does work dumbass check your pc's Bluetooth USB stick adaptor

**Comment by MrCrayfish** [comment]
Try reading this guide on How to Connect a Gamepad
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
