### ISSUE TITLE
Custom keybinds disappear after restart.

### ISSUE THREAD

**Issue by somewhatfrog** [MrCrayfish/Controllable#254]
1.18.1
So I manually added a custom keybind and then set keys to each option.
First bind is for "zoom" option from optifine.
Second bind is for inventory sorter mod.
If I restart the game custom keybind disappear from the list, and I need to add and set them again.

Settings persists only in file, but doesn't show up in game or do anything at all. 

key_adapters.properties
#Key Adapters
#Tue Dec 21 03:41:50 GMT 2021
key.categories.misc=controllable.button.dpad_right
keygroup.inventorysorter=controllable.button.select

Thanks.

**Comment by kindagoose** [comment]
I think this message from the log at the startup is related:
`[Render thread/ERROR]: Error trying to add an option Button to video settings, likely optifine is present which removes vanilla functionality required. The mod still works, but you'll need to manually adjust the config to get different Render distance stretch values as the button could not be added.`

**Comment by WildTom1** [comment]
I have the same problem, I am making a mod pack with my friends, and whenever I add custom binds, they are gone.

**Comment by MrCrayfish** [comment]
This is fixed in the next version. Thanks for reporting.
