### ISSUE TITLE
Appleskin saturation support

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#257]
when you have the console ui style on in controllable, the saturation bar from appleskin doesn't move with it. same with the rest of things from that mod. since appleskin has a system for moving the elements with another mod, maybe you could work something out with it?

**Comment by MrCrayfish** [comment]
I'll look into fixing this since it's quite a common mod.

**Comment by MrCrayfish** [comment]
Closing since it's not something I'll think I can fix 100%, even if I fix with Appleskin, it's likely it's still broken with another mod. Just turn off Console Hotbar.
