### ISSUE TITLE
Quick Move issue

### ISSUE THREAD

**Issue by PConsoleOtaku** [MrCrayfish/Controllable#259]
Quick move work only when bind to B and won't work on any other button

**Comment by yuetsu001** [comment]
Same issue

**Comment by jarrettgilliam** [comment]
Same

**Comment by TheNamesHeckers** [comment]
Same issue when quick moving an item instead of moving it into hotbar or into storage its just another holding items button and drops it when holding it for a certain amount of time

**Comment by TheNamesHeckers** [comment]
[Video as to what happens](https://youtu.be/_cBuFq0qa5k) 

Just thought I'd add a video as to what's happening

**Comment by MrCrayfish** [comment]
This should be fixed in the next update.
