### ISSUE TITLE
Note: Works great on Linux with PS4 controller over bluetooth (Steam drivers)

### ISSUE THREAD

**Issue by hamishmb** [MrCrayfish/Controllable#260]
Hi,

Just a note saying that using the PS4 controller drivers from steam, this works great on Linux with PS4 controllers over bluetooth too :) Perhaps the README could be updated to note this?

**Comment by kyzfrintin** [comment]
Hey dude, could you give an explanation for how you do this? I googled "download linux steam ds4 drivers" and get nothing.

**Comment by MrCrayfish** [comment]
I think it just means install Steam and support will be added automatically. You don't download drivers separately, it comes packaged with Steam.

**Comment by hamishmb** [comment]
Yep, just install steam and enable the PS4 controller support. Shall I submit a PR to note in README.md that it works over bluetooth on Linux too?
