### ISSUE TITLE
Can't use controllers and mouse at the same time.

### ISSUE THREAD

**Issue by thesotman** [MrCrayfish/Controllable#261]
Hi,
I am using the Controllable mod for Minecraft 1.18 and I'm using two controllers and a mouse to play split-screen with three players on one computer.
I enable the two controllers using the Controllable mod, but when I want to use the mouse the one controller gets interrupted from the mouse movement, and I can't get the controller to work without interference from the mouse.

Please help, Thanks.

**Comment by MrCrayfish** [comment]
Make sure "Pause on Lost Focus" is turned off. Press F3 + P while in game to do this.
