### ISSUE TITLE
No input, PS4 cont. Mac

### ISSUE THREAD

**Issue by Enuuii** [MrCrayfish/Controllable#263]
Hey
I’ve got Java 1.18.1 installed on my MacBook Pro and am trying to use a PS4 controller with 0.15.1 of Controllable.
The controller works on Steam (which I’m not running at the same time), and is detected on the Select a Controller page. However I can’t get it to detect any input from the controller, any ideas? I’m at a bit of a loss.
Thanks for your help

**Comment by MrCrayfish** [comment]
I've written a full documentation for Controllable and this includes guides on different methods of connecting your controller. I suggest check it out, and I recommend you looking into the Linux method (Steam Virtual Gamepad) as I have had reports of it working on macOS too, which means you can use the PS4 controller.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
