### ISSUE TITLE
Japanese language support

### ISSUE THREAD

**Issue by KaiseiYokoyama** [MrCrayfish/Controllable#264]
Hello, @MrCrayfish and contributors!
Your work is very helpful for me.

I wish Controllable to support Japanese language and become more useful for Japanese users .
I'm ready to provide `ja_jp.json` for Controllable.

Can I send PR?

**Comment by MrCrayfish** [comment]
Yes you can send a PR

**Comment by KaiseiYokoyama** [comment]
I opened PR #279. Not of all phrases are translated, but the phrases often appear are done. 
@MrCrayfish You can review and merge the PR, or wait a completion of translation. Either is fine.

**Comment by MrCrayfish** [comment]
Any updates on this?
