### ISSUE TITLE
Completely unbind action

### ISSUE THREAD

**Issue by ghost** [MrCrayfish/Controllable#267]
Is there any way that I can completely unbind an action from every button? In vanilla you hit ESC when selecting a keybind, but that button is already taken for canceling a controller button-bind.

**Comment by Hamzabhh** [comment]
I'm also looking for an answer because there's too much key in the binding menu for my controller, but I can't find any answer on the internet...

**Comment by MrCrayfish** [comment]
Sorry, it's not clear. You can right click instead of left clicking and it'll remove the binding. I'll make sure this is more clear in a future update.

**Comment by MrCrayfish** [comment]
I've make this more clear in newer versions of Controllable with a tooltip.
