### ISSUE TITLE
No attack function

### ISSUE THREAD

**Issue by roadhobo** [MrCrayfish/Controllable#270]
With xbox1 controller I cannot attack mobs or pick up items from an item frame using any melee weapons or tools. The R1 button works fine for other things like mining, but no attacks unless I am using a bow.

**Comment by roadhobo** [comment]
This started after the update to 1.18.2

**Comment by theapatra753** [comment]
I am also having this issue. And it's not server side. I can attack with my mouse, but won't let me attack with the controller. Only damage.

**Comment by roadhobo** [comment]
> I can attack with my mouse

Same here, works with mouse. Also can't break torches or crops, basically anything that uses the attack function.

**Comment by aweberlopes** [comment]
Same issue on v1.18.2. Can not attack but can remove blocks.

**Comment by vedforeal** [comment]
Yep the same issue here...
what is wrong??

**Comment by JcMac77** [comment]
Having the same issue. Just updated to the new forge version with 1.18.2 Minecraft and the attack button does nothing against mobs but can break blocks.

**Comment by AirPuffedSugar** [comment]
Chiming in with the same issue. Minecraft 1.18.2, forge version 40.0.17 (most up to date as of this comment). I can break blocks but cannot attack mobs. Attacking works with mouse but not with a controller.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/fe25bba23c15905cca2afe38999f724e255a5500
