### ISSUE TITLE
Not able to attack in 1.18.2 only breaking works

### ISSUE THREAD

**Issue by cruniscavits** [MrCrayfish/Controllable#272]

**Comment by DoigtdePOULET** [comment]
HI! Currently, runing last version of Forge, on 1.18.2, and it does the same. I can break block, but can't use any melee attacks. Bow still work. 

Thanks for your help!

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/fe25bba23c15905cca2afe38999f724e255a5500
