### ISSUE TITLE
[Issue] Epic Fight mod and Fancy Menu

### ISSUE THREAD

**Issue by V4NK0V** [MrCrayfish/Controllable#274]
So, controller support sounds nice, but in my case unfortunately no. Epic fight mod which adds new pretty awesome combat system have bind keys for "dodge" and "switch mining/battle mode" but the second bind isn't working, moreover in that same battle mode player unable to attack like if I use mouse for it.
And about Fancy Menu mod, seems that controllable unable to "see" custom button that I've created, even if I put cursor over it by right  stick

**Comment by MrCrayfish** [comment]
FancyMenu seems to use their own system for rendering widgets, which can't be detected by Controllable. Unless they use the standard system in vanilla Minecraft already, it won't work.
