### ISSUE TITLE
doesnt work on 1.18.2

### ISSUE THREAD

**Issue by crazynerdpc** [MrCrayfish/Controllable#275]
i used to use this often till mc updated and not i cant get it to work at all. i would love to see this mod working again as its one of my favorites.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/fe25bba23c15905cca2afe38999f724e255a5500

**Comment by crazynerdpc** [comment]
ill try it again and let you know! thank you so much!

**Comment by crazynerdpc** [comment]
thank you so much! reinstalling! i love this mod!

**Comment by MrCrayfish** [comment]
The fix is not out, it's just been fixed in code and will have a release soon.

**Comment by Manas-2010** [comment]
@MrCrayfish release it fast
