### ISSUE TITLE
Cannot attack mobs / entities with mod installed 

### ISSUE THREAD

**Issue by AirPuffedSugar** [MrCrayfish/Controllable#276]
minecraft version 1.18.2 
forge version 40.0.17 

Narrowed down issue to the Controllable mod, without it installed I can damage mobs/entities but cannot do so using a controller and this mod. I would love if this bug is fixed as I cannot play with a keyboard/mouse due to medical reasons! 

I suspect the update to 1.18.2 broke the mod in some form.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/fe25bba23c15905cca2afe38999f724e255a5500
