### ISSUE TITLE
Attack button doesn't work on XInput Gamepad (GLFW)

### ISSUE THREAD

**Issue by Voidymite** [MrCrayfish/Controllable#277]
My XBOX controller (or XInput Gamepad GLFW), is perfectly fine and completely compatible with Controllable. However, I cannot hit mobs or players. The bind doesn't work at all. My controller is COMPLETELY functioning, and whenever I bind the attack button to something else, it still does not work. I use default keybinds and no matter what settings I change, this error still proceeds.

**Comment by MrCrayfish** [comment]
Checked closed issues. It's been fixed and is coming in the bug fix release soon.
