### ISSUE TITLE
RT is not working

### ISSUE THREAD

**Issue by Manas-2010** [MrCrayfish/Controllable#278]
When I press RT it's destroying but not attacking

**Comment by Manas-2010** [comment]
plz fix this issue

**Comment by Manas-2010** [comment]
and it's 1.18.2 version that I'm playing

**Comment by MrCrayfish** [comment]
Try a different method of connecting your controller or take a look at the troubleshootng guide.  You can read them here:
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
