### ISSUE TITLE
Dpad UI movement not working

### ISSUE THREAD

**Issue by Gavin456b** [MrCrayfish/Controllable#290]
As the title says, I can't use the DPad to navigate the inventory despite having the bindings set up for it.

**Comment by dude98** [comment]
i've been having the exact same issue, and it is really annoying as using the dpad for the inventory is very important to me.

**Comment by dude98** [comment]
do you have JEI installed? i just realized that when i close jei's item viewer in the inventory (the right side recipe list), i can move with the dpad again.

okay, i just checked and the latest JEI is newer than the latest controllable. after seeing what the oldest compatible jei is with controllable 1.16.0 (jei 9.5.2 is the oldest you can use) and the dpad worked with the jei menu open, so it's an update on jei that breaks the dpad movement.

**Comment by Gavin456b** [comment]
I do, I'll have to test that out today

**Comment by MrCrayfish** [comment]
Is this still a problem?

**Comment by Gavin456b** [comment]
I'm currently using controllable with JEI and I'm able to use my Dpad. So it appears to be fixed
