### ISSUE TITLE
[1.12] Crash trying to integrate Controllable with my custom modpack

### ISSUE THREAD

**Issue by vico93** [MrCrayfish/Controllable#294]
Hello!

I was helping a friend to setup my custom modpack (~103 mods) and he wanted to use Controllable to use his PS5 controller (via DS4Windows) to play the game.

I never used Controllable before, but it was the first option available for 1.12 when i searched on CF, so i indicated it for him to download to his mods folder. At the first the mod ran as intended, but after a while he ran into [this crash](https://gist.github.com/vico93/a03a49115acdd3ef3ba18ca0b543ea9f).

I dont have much to say since i never played it before, so just created this ticket to see if someone can help us about that.

His specs:
Minecraft 1.12.2
Forge 14.23.5.2860 for 1.12.2
Windows 11 x64

**Comment by MrCrayfish** [comment]
Closing as I no longer maintain the 1.12.2 version of the mod.
