### ISSUE TITLE
Breaking Blocks 

### ISSUE THREAD

**Issue by MaxedOut412** [MrCrayfish/Controllable#296]
Breaking blocks in single player in creative takes a few seconds to work and needs my fist to swing around 3 times. Any fix?

**Comment by MrCrayfish** [comment]
Seems to work fine on my end, what controller are you using?

**Comment by MaxedOut412** [comment]
Hey! I’m using an xbox one wireless controller however I have it plugged it in. One think too is it’s only on creative on single player worlds, not sure if I already mentioned that. It has a little delay maybe 2 seconds and 3 punches before the block actually is placed. A normal mouse left click does break instantly though still.

**Comment by MaxedOut412** [comment]
I fixed it! I just had to reinstall an delete all controllable files and reinstall it!
