### ISSUE TITLE
2 controller together?

### ISSUE THREAD

**Issue by piyushbest** [MrCrayfish/Controllable#297]
Me and my brother playing split screen with over 100mods, but my brother can't control every single key as there is too many key but less button, i have 3 controller, 2 xbox and 1 ps2 controller , every controller detect inGame but we cannot bind all 3 controllers to 1 screen(sorry for bad english hope you understand)

**Comment by piyushbest** [comment]
1.16.5 version

**Comment by MrCrayfish** [comment]
Open the game twice, select a different controller for each game from the controller selection list (found from the options menu next to Controls). Turn off "Pause on lost focus" when in game, press F3 + P to do this. If you want to play LAN, you'll need to use different accounts for each game.
