### ISSUE TITLE
My Nintendo Switch Pro Controller is not working

### ISSUE THREAD

**Issue by JCBcounter77** [MrCrayfish/Controllable#301]
I setup my Switch pro controller via Bluetooth to my MacBook Air (it’s from 2021). And it’s not responding to my game in any way. It says  in Minecraft Java that my controller is literally selected but the only button that does anything is the home button and that just takes me to the launchpad, please help me. I am very frustrated as I’ve been trying to work this out for many many weeks.

**Comment by Schweiger-Jacob** [comment]
I had the exact same issue. Using a program called joyshock mapper worked though.

**Comment by skyth540** [comment]
joyshock mapper is only for windows

**Comment by Schweiger-Jacob** [comment]
> joyshock mapper is only for windows

Oh ya……. Maybe there’s an equivalent one for Mac idk.

**Comment by Boitapain** [comment]
please help I have the exact same issue

**Comment by Schweiger-Jacob** [comment]
> please help I have the exact same issue

Steam itself supports the pro controller so maybe adding Minecraft as a nonsteam game could work

**Comment by MrCrayfish** [comment]
Try this guide, even though it says it's for Linux I've had reports it works for macOS too; which means the Switch Pro Controller should be supported.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad
