### ISSUE TITLE
Nintendo Switch Pro Controller goes haywire

### ISSUE THREAD

**Issue by Wheelspawn** [MrCrayfish/Controllable#304]
My Switch Pro Controller works fine on desktop and with Steam, but in-game it goes completely crazy. Constant random button presses make it impossible to do anything, and I obviously can't edit the bindings while the controller is plugged in.

**Comment by MrCrayfish** [comment]
Assuming you are using Windows, install DS4Windows: https://github.com/Ryochan7/DS4Windows/releases/tag/v3.0.18
It tricks Windows into thinking your Swtich controller is an Xbox controller. This is the prefered controller to use if playing on Windows.

**Comment by MrCrayfish** [comment]
You can now use Switch Pro Controller using either DS4Windows or GlosSI. You can read the guides here:
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
