### ISSUE TITLE
Add support for FancyMenu 1.19

### ISSUE THREAD

**Issue by kylepitcock** [MrCrayfish/Controllable#306]
I wanted to move the controller options button into the controls options menu so that it will fit better. However, when I try adding the menu into FancyMenu, it says something along the lines of “this menu doesn’t exist or the mod author needs to add support”. I’m sure that I have the right menu identifier, so please try to add support.

**Comment by MrCrayfish** [comment]
It unfortunately not a priority to support the mod, I don't see myself adding support. I'd rather leave this to someone in the community to create an addon.
