### ISSUE TITLE
[OSX Monterey] Nintendo Switch Pro Controller recognized but not detecting input (Controllable 0.16.0)

### ISSUE THREAD

**Issue by skyth540** [MrCrayfish/Controllable#310]
I tried to connect my switch pro controller over USB, gamepad tester recognized it, but in the mod's options screen it didn't show up. Weird, but oh well

Then I connected with bluetooth, seems to be working better... gamepad tester still picks it up great, and now the controller shows up, checked, in the mod options. However, Minecraft isn't taking any input from the controller. In the Layout menu, the 2 joysticks will ever-so-slightly twitch (randomly, without me touching the controller), but other than that the controller is effectively dead. I can't rebind anything as it just sits listening while I mash buttons

**Comment by Batmanninja1991** [comment]
have you found a fix for this?
im having the same issue with switch pro controller being recognized when plugged and unplugged but does not let you use the controller.
On 2 occasions the controller has worked out of no where but i have yet to figure out how to replicate.

**Comment by skyth540** [comment]
no

**Comment by jooles** [comment]
same issue here :-/ it simple does not recognize any input. 

any news on this? @MrCrayfish :-/

**Comment by MrCrayfish** [comment]
Unfortunately macOS doesn't have good support by default and you need to use Steam for support. Although this guide is for Linux, it has been reported to work on macOS. It allows you to use the Steam Virtual Gamepad, which can be detected by Controllable. https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad
