### ISSUE TITLE
Controllable isn't able to detect my xbox controller 1.19

### ISSUE THREAD

**Issue by Adelade217** [MrCrayfish/Controllable#312]
I have a brachial plexus injury so I can't really use keyboard and mouse to play pc games, so I need a controller to play with like this mod. I have updated my controller, pc forge, fabric, but controllable is not reading my plugged in xbox controller and I wanted to play modded minecraft and I have used both 1.19 versions of controllable.

**Comment by Evolisches** [comment]
Have the same issues with the Mod. Apparently it is because of Version 1.19. 1.18 be working tho.

**Comment by Evolisches** [comment]
Having the same issues with the mod.

**Comment by MrCrayfish** [comment]
I've taken the time recently to write some guides on different methods of connecting your controller to Controllable and troubleshooting on common problems. There should be something there to hopefully solve your problem.

If you're on macOS, try the Linux method on connecting your controller (Steam Virtual Gamepad) as it has been reported to work.

https://mrcrayfish.gitbook.io/controllable-documentation/
