### ISSUE TITLE
Controllers arent recognized on Fedora Plasma

### ISSUE THREAD

**Issue by Evolisches** [MrCrayfish/Controllable#315]
I downloaded the game via the Discover Store, then installed forge and the mod but there are no controllers showning up in the: Select a Controller Menu. I tried The PS4, Xbox 360, Xbox one and the Switch pro controller with non of them Working. Pls Help me :) BTW im on 1.19

**Comment by MrCrayfish** [comment]
Install Steam

**Comment by Evolisches** [comment]
i have steam installed

**Comment by Evolisches** [comment]
What am i supposed to do

**Comment by Evolisches** [comment]
Fixed. You have to download Minecraft over the website in order for it to work (idk why)
