### ISSUE TITLE
Cannot resume both instances

### ISSUE THREAD

**Issue by Bogieloo** [MrCrayfish/Controllable#318]
Whenever i have the 2 game instances, in 1 lan world, multiplayer server or 2 different offline games, i cannot resume both in the same time, whenever one is running, the other can't resume game, tried everything even killing the player to force him to respawn unpaused, did some tricks but it just auto pauses, by pause i mean the esc menu

Game version: 1.16.5
Used controller: 2 generic pc controllers, keyboard used sometimes as a replacement for one player
Mod version: 0.14.1

**Comment by MrCrayfish** [comment]
F3 + P will prevent your game from pausing. Press it while you're in a loaded world. I'll have a patch soon that will remove this process.
