### ISSUE TITLE
Cannot save configurable settings for this mod (custom tooltips, etc.)

### ISSUE THREAD

**Issue by Fuffley** [MrCrayfish/Controllable#319]
Title

**Comment by MrCrayfish** [comment]
Did you press Save?

**Comment by MrCrayfish** [comment]
How are you editing them?

**Comment by Fuffley** [comment]
I press the Controllable icon and go into settings. I am on 16.2 because Optifine can't be used on versions that support 16.3.

**Comment by Fuffley** [comment]
I can go back, however it never saves changes.

**Comment by Fuffley** [comment]
https://cdn.discordapp.com/attachments/368376229679726593/1001975692830982234/2022-07-27_16-11-39.mp4
