### ISSUE TITLE
1.19.1 Crash When Receiving Any Chat Messages

### ISSUE THREAD

**Issue by AuoraMorgan** [MrCrayfish/Controllable#320]
Hello, I made a github account just so I could report this bug.

Since the minecraft update to 1.19.1 yesterday I will crash consistently if any message is received in the chat, whether typed by another user, from the System Admin, or just notifications of players logging on or off. I have tested this by removing all mods (all two of them; Jade, Xaeros Minimap) other than Controllable, and then tried removing even Controllable. Crash doesn't happen with just using Forge without any mods, also doesn't happen with Jade, Xaeros has its' own crash happening also related to text in the chat window.

The error the game gives me when it crashes to launcher is:

The game crashed whilst unexpected error
Error: java.lang.ClassCastException: class net.minecraft.client.GuiMessage$Line cannot be cast to class net.minecraft.client.GuiMessage (net.minecraft.client.GuiMessage$Line and net.minecraft.client.GuiMessage are in module minecraft@1.19.1 of loader 'TRANSFORMER' @70d63e05)
Exit Code: -1

I have attached the crash debug text file, in hopes it'll help you track down the issue. Thank you!

[crash-2022-07-28_20.14.37-client.txt](https://github.com/MrCrayfish/Controllable/files/9215243/crash-2022-07-28_20.14.37-client.txt)

**Comment by marc-ohlmann** [comment]
I am also crashing in 1.19.1 with the same error, except it happens as soon as I push a button on the controller inside a multiplayer game, while connected to my friend's private server. This crash does not occur in singleplayer for some reason.

[crash-2022-07-28_20.58.08-client.txt](https://github.com/MrCrayfish/Controllable/files/9222270/crash-2022-07-28_20.58.08-client.txt)

**Comment by MrCrayfish** [comment]
Avoid 1.19.1 until I release a patch. The 1.19 version is not compatible.
