### ISSUE TITLE
Crash when launching version 11.2, 8.0 working fine

### ISSUE THREAD

**Issue by Desoroxxx** [MrCrayfish/Controllable#321]
Logs: https://www.toptal.com/developers/hastebin/kejivewupo.less

**Comment by MrCrayfish** [comment]
Can you send the full crash log? This small snippet doesn't have all the details I need.

**Comment by Desoroxxx** [comment]
Sadly the crash is too early to generate a crash report but I can provide a full log and a full debug log,

[Log]

Debug log is too long so it is a file instead:
[Debug log](https://github.com/MrCrayfish/Controllable/files/9227994/debug.log)

[Log]: https://www.toptal.com/developers/hastebin/xaburiloqu.sql

**Comment by Desoroxxx** [comment]
Hey, any news on this?

**Comment by MrCrayfish** [comment]
Use an older version of Controllable for a fix.

**Comment by Desoroxxx** [comment]
That's what I am doing but are you planning on fixing this?

**Comment by MrCrayfish** [comment]
I no longer maintain the 1.12.2 version of this mod, so no fix will be coming.
