### ISSUE TITLE
PS4 Controller (D-Pad Not working in inventory and R1 and R2 with JEI)

### ISSUE THREAD

**Issue by jayyms** [MrCrayfish/Controllable#322]
Previously I had Controllable and JEI configured great in Minecraft 16.5 (Forge). The D pad would allow me to navigate around the inventory and I could use R1 and R2 to switch pages for items in the JEI bar. 

However, since installing Minecraft 18.2 (Forge) and updating Controllable and JEI to the correct versions the D-Pad does not navigate in the inventory and I cannot use R1 and R2 (Bindings) for JEI. 

These are the versions:
Controllable: 0.16.0-1.18.2
JEI 18.2-9.7.1.232

I am unsure where the problem is from? I don't understand want I cannot use the control pad in the inventory to move items around.

**Comment by adzam016** [comment]
I have the same issue. I am running 1.18.2 and we are running the Better MC 1.18.2 modpack (also uses JEI). Same issue on server and single player. I can use D-PAD in the menu but not for crafting for some reason. Any help appreciated!

**Comment by orecha5m** [comment]
I am having the same issue with my xbox one controller, running the same versions of both Controllable and JEI.
Both are working fine together in my 1.19 world, but not in my 1.18.2 world.

**Comment by Gavin456b** [comment]
Same issue with xbox controller, D-pad in inventory doesn't work with JEI

**Comment by MrCrayfish** [comment]
Due to how Controllable integrates with JEI, I have to depend on the base JEI mod, which is prone to code breaking changes. JEI simply made some internal changes which broke the code in this mod. Nothing I can do to protect against this but I'll have a patch out soon to address the issue.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/43ca4f8851c33444beef0f38aa37de1942aebe35
