### ISSUE TITLE
Crash when launching game (1.19.1)

### ISSUE THREAD

**Issue by Wh1rledPeas** [MrCrayfish/Controllable#324]
I can't launch the game with the latest version of Controllable.

I'm not getting a crash report, but I'm attaching a fresh set of logs.

[debug.log](https://github.com/MrCrayfish/Controllable/files/9367526/debug.log)
[latest.log](https://github.com/MrCrayfish/Controllable/files/9367527/latest.log)

Any way to get the previous version?

**Comment by MrCrayfish** [comment]
You're using 1.16.5 version on 1.19.1

**Comment by MrCrayfish** [comment]
When using CurseForge, don't press the Download button in the top right. That will just download the latest file uploaded, which may not match the minecraft version you want to download the mod for.

**Comment by Wh1rledPeas** [comment]
> don't press the Download button in the top right. That will just download the latest file uploaded

I see that now. My mistake.  I saw that it was Controllable 0.16.5 and I had 0.16.4.  I just naturally assumed your mod versions were consecutive.
