### ISSUE TITLE
Crashes on 1.16.5 using MultiMC

### ISSUE THREAD

**Issue by MegPredator** [MrCrayfish/Controllable#325]
controllable crashes on launch, Forge: 36.2.34
it crashes if you use your own runtime which is common when using multiMC, so the one by oracle for example, but does not if you use the one in the minecraft launcher in C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\javaw.exe

If you use this runtime in multiMC, it does NOT crash, so it might have to do with the runtime used, all of this happened to someone I talked to on discord which is Wasdeq68, I will attach his log:
[log.txt](https://github.com/MrCrayfish/Controllable/files/9387259/log.txt)

**Comment by Rostas** [comment]
I have this issue aswell
MultiMC 5 0.7.0-3714
Forge: 40.2.0
Minecraft: 1.18.2
Controllable: 0.17.0

**Comment by MrCrayfish** [comment]
@MegPredator user is using Java 18, while they need to use Java 8 for 1.16.5

**Comment by MrCrayfish** [comment]
@Rostas Create a separate issue since this is a 1.16.5 issue. Also include your crash logs
