### ISSUE TITLE
[1.12.2-0.8.0] TTX Tech PS3 controller has Z-Axis and Z-Rotation swapped, registers as 'Piranha xtreme' in-game

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [MrCrayfish/Controllable#326]
I am trying to play on a 1.12.2 server with 0.8.0 of this mod, and the only controller I currently have, a TTX Tech PS3 controller, registers it's Z axes incorrectly. I am having the exact same issue talked about [here](https://steamcommunity.com/discussions/forum/1/2974028351325953978/) with the controller, which as far as I am aware, is an issue known to happen with **PS2** USB controllers, not **_PS3_**, but here we are. Can this be fixed ASAP? I really wish to use the controller to move the camera, without using my mouse. Thanks.

Here is the Hardware ID of my controller, if it helps:

HID\VID_0E8F&PID_0003&REV_0109

Note that the controller uses generic Windows 10 drivers for it, and the axes are set correctly when calibrating it, and the axes work as intended in Genshin Impact, so this is an issue with this mod only.

**Comment by MrCrayfish** [comment]
Closing this issue as I do not maintain the 1.12.2 version of this mod anymore.
