### ISSUE TITLE
[Feature Request] Translation Support

### ISSUE THREAD

**Issue by mjkim0727** [MrCrayfish/Controllable#327]
HUD isn't translated another languages. Here is HUD sample.  (Minecraft BE 1.19.x Win1x Edition, Korean Language)

![Minecraft Screenshot 2022 08 30 - 22 11 13 45](https://user-images.githubusercontent.com/78864678/187445709-129ab89b-5c99-4488-9ac0-dcf85b488f8a.png)

Would you add translation template this mod?

(Example of Official Translations BE HUD - Craft = 제작, Inventory = 소지품, Attack = 공격, etc...)

**Comment by MrCrayfish** [comment]
Well it's not a language I can speak/write, I rely on the community to submit translations.

**Comment by MrCrayfish** [comment]
Korean is now available in this mod.
