### ISSUE TITLE
[Bug] Xbox One S/360 Controller not being detected without Steam on 1.16.5 using Linux

### ISSUE THREAD

**Issue by PeterStrick** [MrCrayfish/Controllable#329]
Using EndeavourOS latest
Kernel: 5.19.4-arch1-1
Minecraft 1.16.5
Controllable Version 0.16.5

The Controller both Wired and Bluetooth is being detected by the KDE Joystick Settings, [gamepad-tester.com](https://gamepad-tester.com/), and Steam, but it is not detected by Controllable.

Hardware Logs are here, including PCI, USB and General Hardware Logs: [eos-log-tool.log](https://github.com/MrCrayfish/Controllable/files/9454195/eos-log-tool.log)

**Comment by MrCrayfish** [comment]
You mentioned the controller is detected on Steam, is it actually enabled since that can help.
![image](https://user-images.githubusercontent.com/4958241/187586529-a4cc4e1f-e15e-48ee-ad4c-4a69ec801d9f.png)

 Unfortuantely a lot of these problems I can't fix because it's the library I depend on which can't detect the controller, not Controllable itself. It could also be the flavour of your OS, simply be that controllers (or specific ones) don't work outside of Steam. Last resort would be to try a different controller if you have one available.

**Comment by PeterStrick** [comment]
> You mentioned the controller is detected on Steam, is it actually enabled since that can help. 

I'm launching the Minecraft Launcher through Steam running in Big Picture mode, Controller plugged in through USB.

Steam detects it as an Xbox One Controller, with and without Xbox Configuration Support enabled.
When launching Minecraft, Controllable detects the Controller as a "Steam Virtual Gamepad" which works fine.

> It could also be the flavour of your OS, simply be that controllers (or specific ones) don't work outside of Steam. 

I tried it with Manjaro before as well with the same behaviour.

> Last resort would be to try a different controller if you have one available.

I have a 3 Controllers so I tried them all with various Settings.
Steam, Minecraft and the Minecraft Launcher were completely closed and re-opened after each Config change
Only Controllable and the SmoothBoot Mod were loaded

Xbox:
Controller | Configuration | Result
| --- | --- | --- |
Official Xbox One S Controller | Minecraft Launcher started normally without Steam | :x: Not detected
Official Xbox One S Controller | All Controller Configuration Support Options Disabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Official Xbox One S Controller | Xbox Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Official Xbox One S Controller | Generic Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Official Xbox One S Controller | Xbox and Generic Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Aftermarket Thrstmaster Afterglow Xbox 360 Controller | Minecraft Launcher started normally without Steam | :x: Not detected
Aftermarket Thrstmaster Afterglow Xbox 360 Controller | All Controller Configuration Support Options Disabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Aftermarket Thrstmaster Afterglow Xbox 360 Controller | Xbox Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Aftermarket Thrstmaster Afterglow Xbox 360 Controller | Generic Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Aftermarket Thrstmaster Afterglow Xbox 360 Controller | Xbox and Generic Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1

Playstation:
Controller | Configuration | Result
| --- | --- | --- |
Official Gran Turismo themed PS4 Controller | Minecraft Launcher started normally without Steam | :heavy_check_mark: Detected as "PS4 Controller" See Screenshot 2
Official Gran Turismo themed PS4 Controller | All Controller Configuration Support Options Disabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Official Gran Turismo themed PS4 Controller | Playstation Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Official Gran Turismo themed PS4 Controller | Generic Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1
Official Gran Turismo themed PS4 Controller | Playstation and Generic Gamepad Configuration Support Enabled in Steam | :heavy_check_mark: Detected as a "Steam Virtual Gamepad" See Screenshot 1

Screenshot 1: ![](https://rawrr.cf/filegallery/LAfu3/HUYUZOjE10.png/raw)
Screenshot 2: ![](https://rawrr.cf/filegallery/LAfu3/SAnopOZu60.png/raw)

Still weird that only Xbox Controllers have Issues without Steam.

**Comment by MrCrayfish** [comment]
To put it simply, it's a GLFW issue, not Controllable. Using Steam is the solution to fix it.

**Comment by Ilovemyhous** [comment]
Hey!
I allow myself to open this up, in case someone stumbles across this.

MC version: 1.19.4
Controllable version: 0.18.0

Note: Steam **wasn't** running during this.
When using my controller with Bluetooth, Controllable doesn't detect it, but works in other games, like [Dolphin](https://github.com/dolphin-emu/dolphin) for example.

Using the controller with Bluetooth:
![image](https://user-images.githubusercontent.com/50217071/230984434-b8d67cb1-82f1-4a6e-bfe8-6914f81aed88.png)

using the controller trough USB:
![image](https://user-images.githubusercontent.com/50217071/230984540-829b1c38-75f9-4510-983e-6af205457fc0.png)

Another note: When using the controller, in Bluetooth, it's detected as a Xbox one controller, and in USB, as a Xbox 360 controller.
