### ISSUE TITLE
MacOS Monterrey (12.4) - Xbox series X controller (2021) connected, detectable by programs, yet unable to be detected by Controllable.

### ISSUE THREAD

**Issue by Frityet** [MrCrayfish/Controllable#331]
Running in 1.18 on the All the Mods 7 modpack. The controller is connected through bluetooth and yet is unable to be detected by the Controllable mod.

**Comment by Frityet** [comment]
I have experience with MacOS development specifically with the "GameController kit", which is the system API for using game controllers. If needed, I am able to make a PR which adds MacOS specific code (native code, using JNI) however I am unsure how to do so.

**Comment by GVonB** [comment]
This issue is persistent with ps4 controllers as well. They are detectable by the mod and show up in menu, however they aren't functional in game despite being fully functional on controller tester sites.

**Comment by brianallenrm** [comment]
I am experiencing the same issue, do you guys were able to solve it?

**Comment by jobukkit** [comment]
> I am experiencing the same issue, do you guys were able to solve it? 

On Fabric you can use LambdaControls instead.

**Comment by SamDS2109** [comment]
Having the same problem on macOS Ventura 13.2

**Comment by MrCrayfish** [comment]
Can you try adding the Minecraft Launcher as a non-steam game, then run the launcher from Steam? I don't have a Mac so I can't debug issues.

**Comment by Frityet** [comment]
> Can you try adding the Minecraft Launcher as a non-steam game, then run the launcher from Steam? I don't have a Mac so I can't debug issues.

Will try

**Comment by MrCrayfish** [comment]
@Frityet Another tip, make sure your controller configuration is enabled in Steam!

**Comment by jobukkit** [comment]
I have not gotten Steam Input to work with any game on Mac OS, so I doubt it will work for this.

**Comment by MrCrayfish** [comment]
1. Add Minecraft Launcher as a non-steam game.
2. Make sure the cofiguration for your controller is enabled in Steam
3. Open Big Picture and run the Minecraft Launcher. 
4. Configured the launcher to not close after launch.
5. Lanuch the game with Controllable installed
6. Profit??

Let me know if these steps work, otherwise I am out of ideas. I recommend Googling Steam Input for non steam games.

Also update to Ventura is possible since it's known to have better gamepad support.

**Comment by MrCrayfish** [comment]
Also try forcing Steam Input to be enabled. Right click the game > Properties > Controller
![image](https://user-images.githubusercontent.com/4958241/219691354-8a4e6501-d8b3-4ab2-a85e-9d870b99bd7d.png)

**Comment by MrCrayfish** [comment]
Also ensure your applicable controller is ticked in settings
![image](https://user-images.githubusercontent.com/4958241/219691739-ccc8cd70-314a-4dfd-a988-55d311d0ef38.png)

**Comment by MrCrayfish** [comment]
It should say if your controller is detected in Steam. If not, your controller is the issue.

![image](https://user-images.githubusercontent.com/4958241/219692384-2039e07a-b619-4372-8324-66f431559719.png)

**Comment by MrCrayfish** [comment]
Here is the full guide. Although it says Linux, it's been reported to work on macOS too.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad

Closing since no updates

**Comment by Salega96** [comment]
Same problem 1.20.1 if use steam big picture its recognized by the map but still no input
