### ISSUE TITLE
Crash with 16.5 for 1.19.2 Using Forge, No other Mods

### ISSUE THREAD

**Issue by onthefritzw** [MrCrayfish/Controllable#332]
Game crashes when loading world. I use Forge, Optifine, and Controllable no other mods. Game runs fine with just Forge, as well as with Forge and Optifine. Using Forge alone with Controllable causes the crash, as well as Forge with Controllable and Optifine. Have the latest versions of all mods and Java. After crash the game generates exit code -805306369.

Thanks so much!

**Comment by iamzachhunter** [comment]
I can second this comment. Minecraft Java crashes on launch when Controllable is the only mod in use.

**Comment by charliebmt** [comment]
mine crashes when i have both controllable and optifine installed

**Comment by crincledpotato** [comment]
I had the same issue, the problem is the latest version of controllable is for Minecraft 1.16.5. The second latest version of controllable supports 1.19.2. It shows the game version supported in the file details.

**Comment by isametry** [comment]
@crincledpotato holy crap you solved my problem! Thank you so much!!

**Comment by crincledpotato** [comment]
@isametry all good bro
