### ISSUE TITLE
Minecraft crashes when opening with 0.16.5 in mod folder through Forge

### ISSUE THREAD

**Issue by efiminzer** [MrCrayfish/Controllable#335]
I want to play with a controller on my PC. Anyone knows how to fix the issue or another way to connect an Xbox controller to PC Minecraft?

**Comment by MrCrayfish** [comment]
For crashes, you'll need to send the full crash log. Otherwise you mention a different method of connecting your controller, you can find guides here: https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
