### ISSUE TITLE
Steam Deck Support

### ISSUE THREAD

**Issue by RossComputerGuy** [MrCrayfish/Controllable#337]
I've tried using this mod with the Steam Deck and I have a few issues:

1. Virtual cursor - why can't I select buttons like with the Midnight Controls mod?
2. Rear buttons - these are not detected
3. Text input - opening the virtual keyboard causes the text box to become deselected with no way to reselect

It would be great to have these improvements as I would like to play FTB modpacks on my Steam Deck and this mod is easy to get added in.

**Comment by MrCrayfish** [comment]
Are you using Steam virtual gamepad?

**Comment by RossComputerGuy** [comment]
No, I have it set to "gamepad with joystick trackpad" so it'll work with the Midnight Controls mod in my Fabric instances.

**Comment by dude98** [comment]
using any steam input mode that uses "A button, B button, etc." is a virtual xbox 360 controller. so you are using steam's virtual gamepad. an option for having the extra buttons work is mapping them to unused keyboard binds (Ex: L4 is numpad1, R4 is numpad2, L5 is numpad4, R5 is numpad5) but then you need to use the keyboard controls menu and bind them.

**Comment by MrCrayfish** [comment]
Following up to mention this is the method to use Controllable with Steam Deck, which has been supported for a while.
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad
