### ISSUE TITLE
When pressing Attack (right trigger), mouse appears on screen, preventing any input

### ISSUE THREAD

**Issue by teneburu** [MrCrayfish/Controllable#338]
Hello,
As the title suggests, at button press my mouse appears, and I can't input anything for half a sec.
I tried to change binding to Lt, it does the same thing with left.
Does not happen with keyboard/mouse.
My forge version is 1.19.2-43.1.32
controllable-0.16.5-1.16.5.jar
I am using Stadia controller with ViGEM bus controller driver and stadia-vigem. Nothing out of place with controller test input.
I'm pretty sure this bug started when I tried to play with Picture-in-picture from my browser but persists even if I close browser, delete controllable files (that i could find) and remake forge installation

PS: It would be great to be able to unbind an action, map it to nothing. Can't do that

**Comment by MrCrayfish** [comment]
Close Steam

Edit: Right click to delete mapping
