### ISSUE TITLE
Ps4 Controller Mapping Not Working

### ISSUE THREAD

**Issue by Squinker1000** [MrCrayfish/Controllable#341]
I’ve connected my ps4 controller to my windows laptop via bluetooth and then I tried usb, and I’ve also tried mapping my controller buttons with Steam as well. Nothing has worked because so far I can only use the circle button, the R2 button, and the right joystick (which is the default when you first connect your controller without mapping it). I’ve also tried the trick where you go in and out of F11 and I still can only use 3 buttons. I downloaded the mod and didn’t fix this issue, can anyone help please? Thank you!

**Comment by dennore** [comment]
I would always prefer using ds4windows if you use DS4 controller via bluetooth.. it converts your controller in a x360 one, and gives you a touchpad

**Comment by MrCrayfish** [comment]
As suggested by dennore, DS4Windows is good method to guarantee support. You can find a guide here and alternative methods too: https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
