### ISSUE TITLE
Inconsistency on Steam Deck

### ISSUE THREAD

**Issue by Ise-no-Kami** [MrCrayfish/Controllable#342]
So, I’ve been trying to use ATLauncher mod packs on Steam Deck. The Controllable mod is absolutely required to do so, but it seems to have different properties depending on the pack. I’ve tried it with three packs so far, here’s what happened:

Vanilla Forge: works perfectly, even gives an option to add extra commands I can bind, though I don’t need it for standard Minecraft.

Pixelmon: works, but that extra command option is gone. Half of all the Pixelmon stuff is extra commands, so that kills any chance of playing that pack.

Explorer’s Modpack: can’t even be loaded in, doesn’t even show up on the CurseForge list when I try. Copying the mod file over from Vanilla or Pixelmon just causes the instance to crash, too.

Does anyone know why the mod is acting so differently from pack to pack?

**Comment by MrCrayfish** [comment]
It's not inconsistency, you're just expierencing different (older) versions of the mod. Please look at the MC version of each modpack. If you want all the latest features, try to find a modpack that runs on MC 1.19.2.
