### ISSUE TITLE
Bind B to backing out of menu

### ISSUE THREAD

**Issue by skybird23333** [MrCrayfish/Controllable#352]
Currently the B button(right button) is not binded to anything except for quick move in the inventory menu. When accessing menus e.g crafting table or pause menu, Y(top button) is used to back out of them instead. It will be a nice improvement if "exiting menu/going back" is a separate action instead binded to B, and in the inventory screen Y can be used for quick move instead, which matches the behaviour on Bedrock Edition.

**Comment by MrCrayfish** [comment]
You can now change this in 0.17.0
