### ISSUE TITLE
Controllable 0.11.2 MC 1.12.2

### ISSUE THREAD

**Issue by LordVardus** [MrCrayfish/Controllable#358]
Hello, is it possible that I could use my Xbox one series x controller because not all buttons work correctly

**Comment by Schwartzyy55** [comment]
I am having same issue. Is there a way for us to fix ourselves? How can we edit the files to fix this? Currently, it detects as a Xbox360 controller (when it should be a Xbox Series Controller). But I tried to just fix the buttons and cannot as it seems one is pressed down all the time. Any tips on how I can do the work to fix it will be appreciated!

**Comment by MrCrayfish** [comment]
Closing as I no longer maintain the 1.12.2 version.
