### ISSUE TITLE
Support for PDP Wired Controller for Xbox Series X

### ISSUE THREAD

**Issue by gcongedo** [MrCrayfish/Controllable#359]
Hello, thanks so much for the fantastic work done in supporting Linux gaming. I read the instructions online and also watched your YouTube video. I am trying to make my PDP controller work on Minecraft Java, but it fails to detect it. The controller is supported natively on Ubuntu 22.04, gamepad-tester.com reports all buttons are working okay, and I have also managed to play some games on RetroArch. At first I thought the problem was that I installed Forge on Minecraft Demo just to test it out, then tried the paid version too: yet the controller is not recognised. I wonder if it is supported by your mod. Could you confirm? Otherwise, please could you help me figure out what might be wrong in my installation? I am desperately trying to set this all up for my son as I would like to have everything ready before Christmas! Any help would be massively appreciated. Thanks for your help. PS: Keep supporting Linux gaming!

**Comment by MrCrayfish** [comment]
Doesn't look like [Game Controller DB](https://github.com/gabomdq/SDL_GameControllerDB) has registered this controller yet. Since it looks brand new, you'll unfortuantely have to wait until the mappings have been submitted.

**Comment by gcongedo** [comment]
Thanks for your help. I'll keep an eye in the next few months then. Please post any updates here.

**Comment by MrCrayfish** [comment]
You can actually create the mappings. Just head over to the [Game Controller DB](https://github.com/gabomdq/SDL_GameControllerDB) and look at their README to see how to create it. You can then submit the mapping to the database.

**Comment by MrCrayfish** [comment]
Here is a direct link to the mapping tool: https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases

**Comment by MrCrayfish** [comment]
The easiest way is to use the Steam method.

**Comment by gcongedo** [comment]
@MrCrayfish Sorry for the delay. I've added the mapping as obtained from AntiMicroX on Ubuntu

**Comment by MrCrayfish** [comment]
I've recently created documentation for Controllable. It's possible the controller will work if you use Steam Virtual Gamepad
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad
