### ISSUE TITLE
Bug: not able to remap controlls on Xbox One S (1708) controller

### ISSUE THREAD

**Issue by SepSol** [MrCrayfish/Controllable#36]
I want to change the default perspective toggle key to perspective toggle key of shoulder surfing mod.

- Minecraft 1.14.4
- Forge 28.1.76
- OptiFine HD U F4
- Controllable-1.14.4-0.6.1
- Xbox One S (1708) Bluetooth Controller

**Comment by MrCrayfish** [comment]
Not a bug

**Comment by SepSol** [comment]
But the controller keybinding option is greyed out in settings for no reason! I thought it might be incompatibility with Xbox wireless controllers.

**Comment by MrCrayfish** [comment]
It's a feature still in the works

**Comment by drizzylga1151** [comment]
any updates on the feature??

**Comment by smhsketch** [comment]
any update on this? it's very annoying how different my controls are on Switch and Xbox than on PC with this mod. Adjustable controls does not seem very hard to make...

**Comment by Swiftrender** [comment]
> It's a feature still in the works

Still?
