### ISSUE TITLE
Crash on Controllable 0.11.2 (v1.12.2) when a button is not mapped.

### ISSUE THREAD

**Issue by auracreepey** [MrCrayfish/Controllable#361]
Hello,
A crash occurs on forge loading screen with Controllable v0.11.2 (v1.12.2) when a button is not mapped.
Remove dinput file resolve the problem.

PS: I cannot assign some buttons of my switch controller (PDP Afterglow wireless deluxe controller), that's why i have this problem.

Hope you can solve this problem

[latest.log](https://github.com/MrCrayfish/Controllable/files/10203311/latest.log)

**Comment by MrCrayfish** [comment]
Closing as I no longer maintain the 1.12.2 version.
