### ISSUE TITLE
D-pad buttons on Xbox one controller causing crashing

### ISSUE THREAD

**Issue by bmward4** [MrCrayfish/Controllable#362]
I have the d-pad buttons bounded the default way but for some reason whenever I press them in the menu or in the game minecraft immediately crashes. Sometimes the buttons will work as intended but mostly it just leads to the game crashing.

**Comment by MrCrayfish** [comment]
Which version of Controllable are you using?

**Comment by bmward4** [comment]
0.16.6 on a 1.19.2 server

**Comment by Kalzares** [comment]
Confirming this is happening to me as well with a couple other controllers. Tested with a Xbox One controller, a Steelseries Duo, and a PS4 controller using DS4. Game crashes immediately after pressing a d-pad button on any of those. Error files attached.

[mc error with ps4 controller.txt](https://github.com/MrCrayfish/Controllable/files/10300814/mc.error.with.ps4.controller.txt)
[mc error with steelseries controller.txt](https://github.com/MrCrayfish/Controllable/files/10300815/mc.error.with.steelseries.controller.txt)
[mc error with xbox controller.txt](https://github.com/MrCrayfish/Controllable/files/10300816/mc.error.with.xbox.controller.txt)

**Comment by AyeAyeRonn707** [comment]
Can confirm this issue with an xbox one series x controller. 

[Crash xbox Controllable mod.txt](https://github.com/MrCrayfish/Controllable/files/10305033/Crash.xbox.Controllable.mod.txt)

**Comment by MrCrayfish** [comment]
Fixed. Update to latest version
