### ISSUE TITLE
DualSense mapping errors 1.12.2

### ISSUE THREAD

**Issue by Num1MarioFan** [MrCrayfish/Controllable#365]
I'm having an error with the mapping of my DualSense controller in 1.12.2 in 1.16.5 and 1.18.2 it works fine, but in 1.12.2 it doesn't want to work, I've tried replacing the GameControllerDB.txt file but it didn't work. I tried using Steam, and that just made the controller's input undetectable to the mod. I really need this fixed as I like playing with Controller in 1.12.2 as most of the great mods are still on 1.12.2 Please help!

**Comment by MrCrayfish** [comment]
Closing as I no longer maintain the 1.12.2 version.
