### ISSUE TITLE
Crash Issue with planetary modpack

### ISSUE THREAD

**Issue by TheRandoGuy** [MrCrayfish/Controllable#366]
Download Planetary (https://www.curseforge.com/minecraft/modpacks/planetary#:~:text=Description%3A,leave%20to%20a%20better%20planet.) and try add the 1.12.2 version compatibility of controllable to it.
When I try load a world or join a multiplayer server with a controller connected, it just crashes. When a controller isn't connected it doesn't crash. 
We believe it is an internal issue and not the modpack itself . Please investigate this

**Comment by MrCrayfish** [comment]
Closing as I no longer maintain the 1.12.2 version.
