### ISSUE TITLE
Xbox Controllers aren't working for me

### ISSUE THREAD

**Issue by Carterkid04** [MrCrayfish/Controllable#367]
I tried using my xbox controllers with the mod and they didn't work. But for some reason my PS4 controller worked via bluetooth.

**Comment by MrCrayfish** [comment]
Try a different method of connecting your controllers. I have written some guides here: https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad

Also consider checking the "Checklist" under troubleshooting for steps to solve issues.
