### ISSUE TITLE
How to toggle the sneak button? 

### ISSUE THREAD

**Issue by LibidinousPsyche** [MrCrayfish/Controllable#368]
It doesn't matter what the main option is under controls it keeps it on toggle, which getting off of a boat you sink. When you go specifically into controllable options there is no such options for toggle/hold just sens ect.

**Comment by MrCrayfish** [comment]
Which version are you using? Only the recent versions have sneak toggle options.

**Comment by MrCrayfish** [comment]
This should be fixed in recent versions of Controllable.
