### ISSUE TITLE
Crash after adding to 1.12.2 modpack

### ISSUE THREAD

**Issue by aliatic** [MrCrayfish/Controllable#369]
I downloaded and installed the 1.12.2 version of the mod tot he modpack folder using the CurseForge app (downloaded from https://www.curseforge.com/minecraft/mc-mods/controllable/files, and then used the "install with CurseForge app" button)

The pack works fine before adding this mod. After adding this mod it immediately crashes after attempting to launch via the launcher. 

I'm going to keep hunting through the forum to see if there are any solutions already listed, but if someone sees this and can offer a quick help (because I'm obviously doing something wrong, surely!) that would be super. Thanks!

EDIT: I don't get a full crash report - only Exit Code 1

EDIT2: I'm understanding that Exit Code 1 is something to do with the Java Runtime - I'm not sure what Conrollable needs; the pack only wants to launch when "use bundled Java runtime" is selected, but whatever that is seems to conflict with Controllable specifically...

**Comment by Zex0208** [comment]
try delete config/controllable 
and delete the mrcrayfish guns mod if you had it

**Comment by MrCrayfish** [comment]
I no longer maintain the 1.12.2 of Controllable.

**Comment by DartisXUI** [comment]
not to necro this, but i just found this mod (and am sort of locked to 1.12.2 due to mod options), and i came across this issue too, but discovered it works with the 0.8.0 version, but not with 0.11.0 and above

not expecting a fix, just hope this helps someone that comes across this (it may not of course, just in case it might...)

**Comment by nycki93** [comment]
> not expecting a fix, just hope this helps someone that comes across this (it may not of course, just in case it might...)

Thank you! Works well enough for me :3
