### ISSUE TITLE
Atm8

### ISSUE THREAD

**Issue by 412anth** [MrCrayfish/Controllable#370]
Is it compatible with atm8 ? Or ever planing on adding compatibility or even collaborate with them to have it in a update bc I tried getting it to work and it just breaks the mod pack and crashes every time

**Comment by MrCrayfish** [comment]
Roughly Enough Items is causing the issue as it's faking JEI being installed when it's not.

**Comment by Raikerzz** [comment]
Hello, I have found out how to use your mod on ATM8. Here is what I wrote on the other topic.
:
Hello, it's not an error but a solution to use Controllable on ATM8. You need to download version controllable-0.16.6-1.19.2. Make sure to check the 'meta inf/mods.toml' file to ensure that it is using the correct version of Forge (43). Once you've done that, it should work. Here's the link to download Forge: https://www.curseforge.com/minecraft/mc-mods/controllable/files/4120620.

Note : I using on ATM8
