### ISSUE TITLE
Needs More Configuration 

### ISSUE THREAD

**Issue by MobsterLobster69** [MrCrayfish/Controllable#371]
As a few other people have mentioned, it would be nice if we could bind "B" ("O" for PlayStation) to back out of menus, as well as make "Y" / "🔺" open inventory and quick add. I also think that you should be able to adjust the X and Y axis sensitivity separately; whenever I adjust the sensitivity of my thumb sticks in the mod, I feel like the Y axis sensitivity is waaay higher than the X axis. Another feature I feel should be added is the ability to use the right thumb stick to scroll up and down in menus. 

Alright that's enough ranting. Really feel like this would make the mod 100x better, but idk how hard it would be to code all this so ¯\_(ツ)_/¯ u do u boo

**Comment by MrCrayfish** [comment]
Features should be available in 0.17.0 now
