### ISSUE TITLE
Annoying paperdoll

### ISSUE THREAD

**Issue by DoubleBoba** [MrCrayfish/Controllable#376]
How to disable PaperDoll in top left corner? Readme says "An example can be found in MrCrayfish's Vehicle Mod", but i cant see anything related there. Why PaperDoll even here? I can't see how it's connected to the purpose of this mod.

**Comment by MrCrayfish** [comment]
It's a feature that was in the Console Edition of Minecraft, you can simply disable it in the config/settings menu.
