### ISSUE TITLE
nintendo switch joycons not being recognized on mac

### ISSUE THREAD

**Issue by zeroesonmars** [MrCrayfish/Controllable#377]
my joycons are both connected to my macbook air and the mod itself runs perfectly fine, my joycons just aren't being recognized when i click the controllable icon in game.

**Comment by MrCrayfish** [comment]
Try using this guide, even though it says Linux it has been reported to work on macOS. This will allow you to use Joycons on macOS. https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad/method-4-steam-virtual-gamepad
