### ISSUE TITLE
when using other mods no controller is reckognized but with only controllable mod it works fine

### ISSUE THREAD

**Issue by CursedFR** [MrCrayfish/Controllable#378]

**Comment by MrCrayfish** [comment]
Can you send your game log? This will let me see if there are any issues when the mods are installed.

**Comment by MrCrayfish** [comment]
I recommend checking out the documentation. It has guides for different methods of connecting controllers and troubleshooting.
https://mrcrayfish.gitbook.io/controllable-documentation/
