### ISSUE TITLE
No Controllers to Select

### ISSUE THREAD

**Issue by Hilpop** [MrCrayfish/Controllable#380]
Despite having controllers that work with my PC, when I try to use one for my game, it doesn't show any controllers to select and bind.

![image_2023-03-22_183714713](https://user-images.githubusercontent.com/128649140/227053892-54d115d5-7919-4261-9bd7-d5f861c08c9b.png)

Yes, the controller is connected when I do this. Does anyone know how I can fix this?

**Comment by MrCrayfish** [comment]
Please read the documentation on how to connect a gamepad. 
https://mrcrayfish.gitbook.io/controllable-documentation/guides/how-to-connect-a-gamepad
