### ISSUE TITLE
Some gui in 1.19.4 is not working.

### ISSUE THREAD

**Issue by Ivanoshechka** [MrCrayfish/Controllable#384]
![image](https://user-images.githubusercontent.com/88715280/228558418-842c0bcf-ccf6-45f0-bffa-2f5570a7853a.png)

So, in 1.19.3 everything is good. But:
In 45.0.29 forge on 1.19.4 buttons guides with doll is missing.

I checked 45.0.25 - same total.
![image](https://user-images.githubusercontent.com/88715280/228559827-f5d51879-edf7-4ef4-bb8c-830a7e148774.png)

All settings for it are set.

https://user-images.githubusercontent.com/88715280/228561500-27f3c136-259c-41c8-beb4-77b99c1e8282.mp4

**Comment by MrCrayfish** [comment]
Fix coming soon!

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/30ea131b3a50daf16cb93a106dcce4190a3887f5
