### ISSUE TITLE
Radial Menu invisible?!

### ISSUE THREAD

**Issue by dennore** [MrCrayfish/Controllable#385]
When i press ➡️, i dont see a radial menu… i just hear a pop sound and my right stick is not moving the camera, but popping sound when i rotate it… when i press ➡️ again. I can move my camera again… should there be a menu showing?

im using  forge 45.0.27, mc 19.9.4 , and latest controllable for 1.19.4

**Comment by dennore** [comment]
Updated to latest version fixed it for me

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/30ea131b3a50daf16cb93a106dcce4190a3887f5
