### ISSUE TITLE
Button to craft a stack?

### ISSUE THREAD

**Issue by dennore** [MrCrayfish/Controllable#386]
Is there a keybind to place a stack in craft window from recipe list?

I only found press A (circle)... but not for placing em... like when you play m/k and press SHIFT+click

**Comment by MrCrayfish** [comment]
Controllable uses a fake click on the book and the crafting output to achieve quick crafting. Since the game only supports either crafting one or all, I won't be able to add support for just one stack.

**Comment by MrCrayfish** [comment]
If you're after "craft all" feature, it may be possible to implement this.
