### ISSUE TITLE
Controller not detected of Bluetooth, but over USB.

### ISSUE THREAD

**Issue by Ilovemyhous** [MrCrayfish/Controllable#388]
Hey!
This will be most likely a duplicate of [this](https://github.com/MrCrayfish/Controllable/issues/329), but I'd rather pull that up again, in case something has been found by now.

MC version: 1.19.4
Controllable version: 0.18.0

Note: Steam **wasn't** running during this.
When using my controller with Bluetooth, Controllable doesn't detect it, but works in other games, like [Dolphin](https://github.com/dolphin-emu/dolphin) for example.

Using the controller with Bluetooth:
![image](https://user-images.githubusercontent.com/50217071/230984434-b8d67cb1-82f1-4a6e-bfe8-6914f81aed88.png)

Using the controller trough USB:
![image](https://user-images.githubusercontent.com/50217071/230984540-829b1c38-75f9-4510-983e-6af205457fc0.png)

Another note: When using the controller, in Bluetooth, it's detected as a Xbox one controller, and in USB, as a Xbox 360 controller.

_Originally posted by @Ilovemyhous in https://github.com/MrCrayfish/Controllable/issues/329#issuecomment-1502236075_

**Comment by MrCrayfish** [comment]
This is not something I can solve in Controllable, I use GFLW to grab gamepad input. I would explain but I've already written some guides on different methods of connecting your controller, which will solve this issue.
https://mrcrayfish.gitbook.io/controllable-documentation/

**Comment by MrCrayfish** [comment]
It's possible the mappings do not exist in the SDL Game Controller database for the bluetooth version. Check the readme of their project to find tools to read the GUID of your device, which you can compare in the [gamecontrollerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)
https://github.com/gabomdq/SDL_GameControllerDB

**Comment by Ilovemyhous** [comment]
Alright, thanks, and keep up the good work!
