### ISSUE TITLE
No detected Gamepads on Steamdeck

### ISSUE THREAD

**Issue by jhNsXO** [MrCrayfish/Controllable#392]
Since your switch to LibSDL4J in 0.19.0, Controllable doesn't detect the steamdeck buttons as a virtual controller. (ie the input device list is empty)
Reverting back to 0.18.1 fixes the issue, so I'm assuming the problem lies with the library change in 0.19.

cheers

**Comment by MrCrayfish** [comment]
Dang, I was really hoping LibSDL4J would be a good change since I get direct access to SDL2. Might have to revert back to GLFW for stability. Any chance you can send me your game logs? It's possible the natives didn't load.

**Comment by jhNsXO** [comment]
Hey, sure. I hope these are the right ones.
0.19.2: https://mclo.gs/2j7gq4v
0.18.1: https://mclo.gs/Oikl12s

**Comment by MrCrayfish** [comment]
Interesting enough, SteamOS is suppose to have SDL2 installed by default. I can see in the logs too that mappings were updated, so it's clear the natives are loading (and working correctly). Were there any differences when you ran 0.19.0 compared to 0.18.1 (in terms of configuration)?

**Comment by jhNsXO** [comment]
Nope, nothing that I am aware of. I currently have both installed in Prism Launcher. Just deactivated one, and activated the other between the two logs.

It's also the same non-steam entry, so no difference between the steam controller settings. (Controller Layout is Gamepad + Mouse Trackpad)

**Comment by MrCrayfish** [comment]
I can potentially try downgrading SDL to an older version since I am using a quite recent version of the library. Would you be willing to test it and send the logs back?

**Comment by jhNsXO** [comment]
Yeah sure :)

**Comment by MrCrayfish** [comment]
Actually, I might have found the cause. I never initialized the required modules in SDL to get gamepad input -_- I'll still send you a test version since I'd like to know if it definitely works on SteamDeck.

**Comment by MrCrayfish** [comment]
[controllable-0.19.3-1.19.4-release.zip](https://github.com/MrCrayfish/Controllable/files/11355632/controllable-0.19.3-1.19.4-release.zip)

Let me know how it goes. Jar file is inside of the ZIP

**Comment by jhNsXO** [comment]
Just tested it. Gamepad shows up in the Controller settings, and after some playing everything seems to be working fine / just like in 0.18.1.

So cheers, you seem to have fixed it :)

(Here is the log if you want it for w/e reason https://mclo.gs/MnjdaAL Though everything seems to be working)

**Comment by MrCrayfish** [comment]
Update has been published now. Thanks for your help
