### ISSUE TITLE
The virtual cursor does not work on fabric for me

### ISSUE THREAD

**Issue by KennyDevT** [MrCrayfish/Controllable#402]
The title
on fabric 0.14.19

**Comment by KennyDevT** [comment]
i found out that any version of the fabric api which  is above version 0.80.0 does not work
but the bug is still there on quilt unfortunately

**Comment by KennyDevT** [comment]
here is the changelog for fabric api 0.81.0 if it helps 


    Bump version (modmuss50)
    Convention Tags Improvements (#3051) (Technici4n, modmuss50)
    Add TAWs for DamageSources (#3048) (Technici4n, modmuss50)
    Remove texture indices and make material AO a TriState (#3044) (Technici4n, PepperCode1)
    Fix getName for builtin packs not returning an internal name (#3047) (Technici4n)
    Improve transfer API debug messages (#3049) (Juuz)
    Terminally deprecate EventFactory isProfilingEnabled and invalidate (#3050) (Technici4n)
    Add some new TAWs for tree worldgen (#3060) (Maity)
    Fix screen api passing wrong MatrixStack to render events (#3061) (Xander)

**Comment by KennyDevT** [comment]
Fixed

**Comment by SilentException** [comment]
@KennyDevT mind sharing more info? The virtual cursor isn't showing for me on 1.19.4 fabric instance with Controllable 0.19.2 but it is working on 1.20.1 one (newer Controllable)..

**Comment by KennyDevT** [comment]
Yeah that's what i meant

**Comment by SilentException** [comment]
But how is it fixed? You upgraded to 1.20.1 or did you fix it somehow on 1.19.4?

**Comment by KennyDevT** [comment]
I mean it was fixed in the new update
