### ISSUE TITLE
game crashes when I try to run mc with controllable

### ISSUE THREAD

**Issue by archemids** [MrCrayfish/Controllable#410]
I recently installed the newest forge update along with the controllable 1.20 update, but when I try to run mc it immediately crashes and hits me with an "error game crashed" . I ran mc with forge on its own without controllable and the game loaded fine. is this a an issue with the controllable mod? because its new or is it forge .

**Comment by k5TRY** [comment]
Be sure framework is installed. Controllable depends on it.

**Comment by MrCrayfish** [comment]
Just to clarify, Controllable now depends on Framework in 1.20.1 and above.
