### ISSUE TITLE
Crash with exit code 1

### ISSUE THREAD

**Issue by StijnPaepe** [MrCrayfish/Controllable#412]
Hello, I am kind of new to this, but version 1.19.3 worked from the first try.
I am using forge version: 1.20.1-forge-47.0.3 and both controllable versions: controllable-forge-1.20.1-0.20.0 and controllable-forge-1.20.1-0.20.1 make my game crash with exit code 1.
Any ideas what I could be doing wrong or is it a known issue?
Kind regards :) 

Edit: after checking the discord server I found out I needed Framework to be installed and that fixed it thx for this awesome mod :)

**Comment by Stoffss** [comment]
Can you give a link to the framework? I need it too and dont know what to dl

**Comment by joaopatrocinio** [comment]
> Can you give a link to the framework? I need it too and dont know what to dl

https://www.curseforge.com/minecraft/mc-mods/framework/files/4590795
