### ISSUE TITLE
Dont work on Steam Deck - just gives the following error and need help going past

### ISSUE THREAD

**Issue by Stoffss** [MrCrayfish/Controllable#413]
Im trying to get this working so my kids can play the latest version of MC on their Decks..

Thank you in advance!

Running Prism Launcher 7.1
Java 17
Minecraft 1.20.1
Forge 46.0.14
Controllable 0.20.1

----------------------------------------------------------------
Error log:

Prism Launcher version: 7.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.9.55.46, 65.9.55.79, 65.9.55.8, 65.9.55.49]

session.minecraft.net resolves to:
    [13.107.246.53, 13.107.213.53, 2620:1ec:bdf::53, 2620:1ec:46::53]

textures.minecraft.net resolves to:
    [13.107.213.53, 13.107.246.53, 2620:1ec:46::53, 2620:1ec:bdf::53]

api.mojang.com resolves to:
    [13.107.213.53, 13.107.246.53, 2620:1ec:bdf::53, 2620:1ec:46::53]

Minecraft folder is:
/home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Minecraft 1.20/.minecraft

Java path is:
/app/jdk/17/bin/java

Java is version 17.0.7, using 64 (amd64) architecture, from Flathub.

AMD Custom APU 0405
Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405] (rev ae)

Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 0123

Kernel driver in use: amdgpu

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Minecraft 1.20/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.1/lwjgl-glfw-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/mmc2/ForgeWrapper-mmc2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.6/securejarhandler-2.1.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/forgespi/7.0.0/forgespi-7.0.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/fmlloader/1.20-46.0.14/fmlloader-1.20-46.0.14.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Mods:
  [✔] controllable-forge-1.20.1-0.20.1
  [✘] ferritecore-6.0.0-forge.jar (disabled)
  [✘] rubidium-0.6.5.jar (disabled)
  [✘] Xaeros_Minimap_23.4.4_Forge_1.20.jar (disabled)

Params:
  --username  --version 1.20.1 --gameDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Minecraft 1.20/.minecraft --assetsDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 46.0.14 --fml.mcVersion 1.20 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230608.053357

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Djava.net.preferIPv4Stack=true, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 693

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2023-06-16 22:56:57,829 main WARN Advanced terminal features are not available in this environment
[22:56:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Stofffs, --version, 1.20.1, --gameDir, /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Minecraft 1.20/.minecraft, --assetsDir, /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets, --assetIndex, 5, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 46.0.14, --fml.mcVersion, 1.20, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230608.053357, --width, 854, --height, 480]
[22:56:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7 by Flathub; OS Linux arch amd64 version 5.13.0-valve36-1-neptune
[22:56:58] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23140!/ Service=ModLauncher Env=CLIENT
[22:56:58] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/fmlcore/1.20-46.0.14/fmlcore-1.20-46.0.14.jar is missing mods.toml file
[22:56:58] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/javafmllanguage/1.20-46.0.14/javafmllanguage-1.20-46.0.14.jar is missing mods.toml file
[22:56:58] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/lowcodelanguage/1.20-46.0.14/lowcodelanguage-1.20-46.0.14.jar is missing mods.toml file
[22:56:58] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/minecraftforge/mclanguage/1.20-46.0.14/mclanguage-1.20-46.0.14.jar is missing mods.toml file
[22:56:59] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 1 dependencies adding them to mods collection
[22:56:59] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'framework', Requested by: 'controllable', Expected range: '[0.6.5,)', Actual version: '[MISSING]'
	Mod ID: 'minecraft', Requested by: 'controllable', Expected range: '[1.20.1,)', Actual version: '1.20'
	Mod ID: 'forge', Requested by: 'controllable', Expected range: '[47.0.3,)', Actual version: '46.0.14'
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.module.ResolutionException: Module minecraft reads another module named minecraft
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:719)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 16 Jun 2023 22:57:15 +0200

**Comment by MrCrayfish** [comment]
You need 1.20.1, not 1.20. You're also missing Framework dependency

**Comment by Stoffss** [comment]
Minecraft is at 1.20.1
What kind of framework dependency do you mean? Will a move to java 19 solve that?

**Comment by Stoffss** [comment]
thank you for your work btw! My kids love your mods

**Comment by Stoffss** [comment]
Ok, I solved it... Framework is a MOD available in Forge! added it and now kids are happy!

Thank you for your excellent work with all your mods! Its extremly appriciated!
