### ISSUE TITLE
Eating/ Holding Interact Issue

### ISSUE THREAD

**Issue by Kodealamode** [MrCrayfish/Controllable#419]
When I hold left trigger to eat or pull back bow it acts as if I am taping interact over and over. This a known issue?

**Comment by ryankrumins** [comment]
I found the same with mod version 0.19.0 on xbox 360/one wired controllers, but it works fine in 0.19.3 so try a different version if possible.

**Comment by MrCrayfish** [comment]
This was a bug in 0.19.0 and has since been fixed in newer versions
