### ISSUE TITLE
Virtual Cursor not appearing

### ISSUE THREAD

**Issue by ParkerTCK** [MrCrayfish/Controllable#438]
using fabric 1.19.4, mod version 0.19.2

as the title says, my virtual cursor isnt appearing, yet its still there since i can still press buttons with it

its not an incompatible mod issue since i removed all my other mods besides fabric api, framework, catalogue, and of course the mod itself
it worked before i tried plugging in a second controller for splitscreen, but once i plugged it in the virtual cursor became invisible and even after unplugging controller 2 and restarting minecraft i still had the same problem

**Comment by ParkerTCK** [comment]
i finally figured it out, use fabric version 0.80.0 or lower, it cant be any newer than that

**Comment by ParkerTCK** [comment]
i finally figured it out, use fabric version 0.80.0 or lower, it cant be any newer than that

**Comment by CryoNine** [comment]
> i finally figured it out, use fabric version 0.80.0 or lower, it cant be any newer than that

Do you mean 0.8.0? It's been a year and the newest version is 0.16.0
