### ISSUE TITLE
Incompatibility with Create: Tweaked Controllers

### ISSUE THREAD

**Issue by getItemFromBlock** [MrCrayfish/Controllable#445]
Hello, I am the developer of the Create: Tweaked Controllers mod (a Create mod addon) for Minecraft 1.18.2 and Forge.

Someone reported [an issue](https://github.com/getItemFromBlock/Create-Tweaked-Controllers/issues/2) on my mod.  
The problem is that when you use the controller, it is supposed to cancel all of the inputs that are bound to both the controller and the game. It is worth noting that in order to achieve controls that could be bound to a keyboard, a mouse button/cursor or a gamepad I had to implement my own input system (which does not replace Minecraft's system, I only use it with the controller item).
The consequences are that you can still move around when using the controller, which is problematic as the joystick will control both the player movement and the controller item's joystick.

From what I see in your code, you are overriding the value of the key based of what you read from the controller
[This part](https://github.com/MrCrayfish/Controllable/blob/1.18.X/src/main/java/com/mrcrayfish/controllable/mixin/client/KeyMappingMixin.java#L21) could be the culprit.
I am writing this as I am not sure how can I best take on this issue, more precisely what can I do on my side.

Thanks in advance

**Comment by getItemFromBlock** [comment]
I just saw the developers section in the README, I will try tomorrow to properly cancel the events on my side, and I will update this depending on the result.

**Comment by MrCrayfish** [comment]
You should be able to cancel movement with Forge's MovementInputUpdateEvent

**Comment by getItemFromBlock** [comment]
Alright I just cancel the ButtonInput, Move and Turn events (as they are used by the Controller) except for the use key (usually left trigger) to still let people put down the controller.
This is not ideal, as it make one input unavailable on my side and it prevents moving the player and the camera, but it works
Also I made it show the use button as "exit controller" when you are using it

**Comment by getItemFromBlock** [comment]
Unless you have a better idea, I think I will close this
