### ISSUE TITLE
Doesn't work Correctly on Ubuntu 18.04.3 and Ubuntu 19.10

### ISSUE THREAD

**Issue by CrispyBuns** [MrCrayfish/Controllable#45]
Every Time I Launch It In Forge It Boots Like Normal And then It crashes
Works Fine On Windows

**Comment by CrispyBuns** [comment]
Btw I don't have My Ubuntu 18.04.3 installation since I reinstalled and upgraded to 19.10

**Comment by MrCrayfish** [comment]
Thanks for sending the crash report, I clearly know what the problem is!
