### ISSUE TITLE
Controller input does not send update to os resulting in screen lock

### ISSUE THREAD

**Issue by Shadowblitz16** [MrCrayfish/Controllable#455]
My computer goes to sleep while playing minecraft using a xbox360 red rock candy controller.
It's not notifying the os of input.

I'm on kubuntu 22.04 with...
- multi mc: 0.7.0-3809
- forge: 47.1.0 
- framework: 0.6.16
- controllable 0.20.3

**Comment by MrCrayfish** [comment]
Unfortunately not something I can fix and sounds like a specific OS issue. I would recommend just extending your time before screen lock.
