### ISSUE TITLE
Compatibility Issue with the Mod Timeless and Classics (gun mod) on 1.18.2 and 1.16.5

### ISSUE THREAD

**Issue by EarthKing339** [MrCrayfish/Controllable#478]
The title is self explanatory, but basically, the attack and aim buttons do not make the guns fire. I use a dualsense, and when I hold L2, it doesnt aim. When I press R2, it doesnt fire, it just breaks the block in front of me as if i was using my hand. Please fix.

**Comment by bigspeezy** [comment]
@EarthKing339 I was having this very same issue today on 1.18.2, but using a PDP Wired Gamepad for Xbox One. 

I redid everything in 1.16.5 and the aim and shoot works great now. The rt was still breaking blocks while shooting if I was close enough to it, so I disabled the Attack/Destroy Button under Gameplay. Now when holding a weapon rt shoots, when holding anything else, it breaks.

**Comment by EarthKing339** [comment]
@bigspeezy Two things: one, would that work in 1.18.2 and two, please give detailed instructions on how to do it.

**Comment by MrCrayfish** [comment]
Timeless and Classics is an independent mod. You'll have to report the issue to them.
