### ISSUE TITLE
@EarthKing339 I was having this very same issue today on 1.18.2, but using a PDP Wired Gamepad for Xbox One.

### ISSUE THREAD

**Issue by EarthKing339** [MrCrayfish/Controllable#487]
@EarthKing339 I was having this very same issue today on 1.18.2, but using a PDP Wired Gamepad for Xbox One. 

I redid everything in 1.16.5 and the aim and shoot works great now. The rt was still breaking blocks while shooting if I was close enough to it, so I disabled the Attack/Destroy Button under Gameplay. Now when holding a weapon rt shoots, when holding anything else, it breaks.

_Originally posted by @bigspeezy in https://github.com/MrCrayfish/Controllable/issues/478#issuecomment-1837348091_

**Comment by EarthKing339** [comment]
@bigspeezy come back help me

**Comment by bigspeezy** [comment]
@EarthKing339 Sorry for the delay in response! Been wildly busy. I am trying to remember the details, but essentially: I was unable to get any combination of Timeless & Classic Guns/Controllable to function correctly in any other MC version than 1.16.5

What is your platform? Windows/Mac

**Comment by MrCrayfish** [comment]
Timeless & Classic is an independent mod. It is up to authors of that mod to resolve the issue. This is not the correct place to discuss it.
