### ISSUE TITLE
Cannot move items in inventory v0.6.1 and 0.7.0

### ISSUE THREAD

**Issue by BK119** [MrCrayfish/Controllable#50]
Attempted to use your mod to play split screen 

However, whenever player two, using a controller, attempts to pick up an item in inventory, it attaches to the actual mouse instead of the virtual mouse

Have attempted with or without your mod on the keyboard screen, same result.

**Comment by juicyboii** [comment]
Having the same issue. but with a single player not split screen. Can't pick anything up because it snaps to the mouse. The mouse is also still on screen if inside an inventory or menu; even while moving the controller cursor around

**Comment by FusionLord** [comment]
if you change cursor type to console you can see where the virtual cursor is, and still move items.

**Comment by MrCrayfish** [comment]
Do you have Optifine installed?

**Comment by TinyPandas** [comment]
I am experiencing this same issue using version 0.6.1 on 1.12.2. I have optifine installed, is there a fix, or is that a conflict?

**Comment by MrCrayfish** [comment]
This should be fixed in recent versions (0.10.1). Optifine patched the same class I was modifying but now I use Mixins and it allows me to patch with Optifine still working.
