### ISSUE TITLE
Low FPS breaks inventory selection with D-Pad

### ISSUE THREAD

**Issue by NickHam13** [MrCrayfish/Controllable#505]
Using latest Fabric version, playing at any FPS below 40 makes selecting items with the D-Pad bug out

**Comment by MrCrayfish** [comment]
In the config, try changing "fpsPollingFix" to true to see if it helps.

**Comment by NickHam13** [comment]
I have tried with it both enabled and disabled, even on Forge and it doesn't work there either. However, I know for a fact that this issue doesn't exist on at least 1.18.2, when I originally used this mod. I'm very certain that the issue doesn't lie with me here, unless you have any other ideas. Also, I also ask that if you end up fixing this, please backport to 1.20.1, I'd appreciate it greatly.

Windows 10
Prism Launcher 8.2
LWJGL 3.3.2
Minecraft 1.20.1
Intermediary Mappings 1.20.1
Fabric Loader 0.15.7
Fabric API 0.92.0+1.20.1
Framework 0.6.27
Controllable 0.20.2
