### ISSUE TITLE
Xbox 360 Use Item function broken in 1.5.1

### ISSUE THREAD

**Issue by hellothere2** [MrCrayfish/Controllable#54]
Pressing or holding the left trigger will cause the item to continuously be used as if the user were rapidly right-clicking instead of holding. This breaks all usable items on the Xbox 360 controller.

Increasing the dead-zone on the xbox controller to 0.15 fixes the deadzone issue.

Running minecraft+forge+controllable in 1.5.1, no other mods. Using a USB Xbox 360 controller bought directly from a physical windows store location, so it's not a knock off.

Mod detects my controller as "ShanWan PS3/PC Wired GamePad" and gives no other controller options + the option to remap buttons is grayed out and cannot be pressed.

**Comment by MrCrayfish** [comment]
Is this an issue on the latest version? Check for latest update because I just pushed one recently

**Comment by Barberfluids** [comment]
> Is this an issue on the latest version? Check for latest update because I just pushed one recently

This is an issue with 1.12.2 version that was released in February.

**Comment by WotblitzMC** [comment]
Don't know where it's getting "ShanWan PS3/PC Wired GamePad". I'm currently developing a fabric port, on dev the console, it says for me: "Joystick 0: XINPUT: Xbox 360 Controller" just before "ShanWan PS3/PC Wired GamePad"(Will not show in game log file). Using a PS3 controller with Xbox 360 emulating drivers.

**Comment by MrCrayfish** [comment]
Closing because stale. Reopen if still an issue on the latest version.
