### ISSUE TITLE
Better inventory navigation and crafting

### ISSUE THREAD

**Issue by kaphula** [MrCrayfish/Controllable#55]
Hello,

I tried this mod and noticed that the inventory management is not as swift as on Nintendo Switch edition, for example. The main issues for me were the lack of precise grid navigation with d-pad and the crafting process when selecting craftable items from recipe book.

Is it true that currently there is no way to craft items instantly from within the recipe book, but instead it is required to move the cursor on top of the item that will be crafted and select it manually? I looked quickly at the source code, and from what I understood, the mod simply binds existing minecraft inventory shortcut functions to controller buttons, so no external inventory management functionality is currently implemented?

Would it be even possible to implement custom inventory functionality like crafting items instantly from the recipe book and is the purpose of this mod to explore implementing such new features in the future?

**Comment by DanKruse731** [comment]
I second this request. If these features are added, then this mod would be perfection.

**Comment by tcardlab** [comment]
I agree

**Comment by ClaudiusMinimus** [comment]
I too would love to see precise grid navigation with the d-pad.

**Comment by timsama** [comment]
Lack of dpad support is my number 1 complaint about Java edition, so for me, adding this would be huge.

**Comment by MrCrayfish** [comment]
In 0.10.1 you can now navigate with DPAD buttons!
