### ISSUE TITLE
Minecraft Crashes!

### ISSUE THREAD

**Issue by hoostelstudios** [MrCrayfish/Controllable#56]
Hello, When i try to get into 1.15.1 with controllable installed it says "INVALID AXIS IN GAMEPAD MATCHING", but when i try to get in 1.14.4 it crashes when i join an world or server. I can only play 1.12.2 using controllable v3.1, otherwise its the same as 1.14.4. How can i solve this issue?
Btw on my joystick i can't look around even though it has the "circle buttons" on it. My joystick is jetion jt-u5540, but it shows that its G-Shark GS-GP702.

**Comment by MrCrayfish** [comment]
You can't use a joystick, only gamepads.

**Comment by HystelStudios** [comment]
Ok
