### ISSUE TITLE
Controls do not match bedrock edition (1.12 version - 0.6.1)

### ISSUE THREAD

**Issue by barmonger** [MrCrayfish/Controllable#57]
The controls do not seem to match the controls from the Windows 10 edition of Minecraft.
Only played around with it for a little while, but it seems to be missing some things.

No 'back' button. I think we use B/red for that on an xbox controller, which is often used as a cancel/back button.
Close inventory is the same button as open inventory. It should be the 'back' button mentioned above.
The snap-to-grid functionality is counter-intuitive in many cases.
There seems to be some mix-up in the select/move/place  butons when performing the action for a stack/single item. I often chose the wrong one when trying to do the same thing in different inventory/crafting menus and I remember them to be the same button on the windows 10 version.

Is the 1.12 version of Minecraft still being supported by this mod?
If so, I can go through the buttons in Win10 and compare them to the mod and make a proper list.

**Comment by MrCrayfish** [comment]
Not designed to match
