### ISSUE TITLE
Game Crashed upon creating new world

### ISSUE THREAD

**Issue by Stonkkkkkkksssss** [MrCrayfish/Controllable#59]
When i create a new world, it loads for a little bit then crashes, i don't know how i fix this and i've tried multiple times and it still won't work. Crash Report :
[crash-2020-01-15_20.26.34-server.txt](https://github.com/MrCrayfish/Controllable/files/4069055/crash-2020-01-15_20.26.34-server.txt)

**Comment by MrCrayfish** [comment]
Not my mod
