### ISSUE TITLE
Camera movement stutters when framerate is low [0.7.2]

### ISSUE THREAD

**Issue by valentyn-l** [MrCrayfish/Controllable#62]
Camera movement stutters regardless of controller connected on version 0.7.2, with and without Optifine. The higher the framerate, the less noticeable the stutter. 

If capping framerate at 60fps, the stutter is extremely distracting.

**Comment by MrCrayfish** [comment]
Have you got additional software or mods installed?

**Comment by valentyn-l** [comment]
No. Just the latest Minecraft Forge (tested with most recent and older versions). Running Optifine alongside Controllable makes no change.

**Comment by MrCrayfish** [comment]
Fixed in 0.8.0
