### ISSUE TITLE
Reproducible crash under Linux with the xbox one controller

### ISSUE THREAD

**Issue by Volker-Weissmann** [MrCrayfish/Controllable#65]
Hi, Minecraft keeps crashing with the following message:

The game crashed whilst initializing game
Error: java.lang.IllegalStateException: GLFW error before init: [0x10004]Invalid button in gamepad mapping 050000005e040000fd02000003090000 (Xbox One Wireless Controller)
Log file:
[crash-2020-02-22_22.00.07-client.txt](https://github.com/MrCrayfish/Controllable/files/4239935/crash-2020-02-22_22.00.07-client.txt)

My System:
OS: Arch Linux
Java: openjdk 13.0.2 2020-01-14
Forge version: 1.15.2-31.1.0
I'm using the xbox one controller via bluetooth

**Comment by shymega** [comment]
Can reproduce here as well. Works fine on Windows.

**Comment by AVonGauss** [comment]
As a workaround, I believe the xpadneo driver or xow project both located on Github do not exhibit this behavior.

**Comment by MrCrayfish** [comment]
This is a driver issue, not my mod.

**Comment by shymega** [comment]
Unfortunately, the two drivers aforementioned have not fixed the issue. Looking at the stack trace, it would seem that either GLFW _or_ LWJGL are responsible. I'm on 1.15.2, on Arch, connected to the controller via Bluetooth.

**Comment by Volker-Weissmann** [comment]
Do you have a link to the drivers issue?

**Comment by shymega** [comment]
I'm not sure what you mean by that. By 'issue', I meant this issue here. Although if its not the mod, I'm not sure what the cause is.

**Comment by Volker-Weissmann** [comment]
You said that 
> Unfortunately, the two drivers aforementioned have not fixed the issue. 
So I assumed that you opened an issue in the bugtrackers of GLFW or LWJGL.

**Comment by shymega** [comment]
No, i just meant that I tried using the two controller drivers mentioned before, and rebooting to make sure it had installed, to no avail. Its a bit odd...

**Comment by Volker-Weissmann** [comment]
Ok. I think I will just continue using Mouse+Keyboard

**Comment by tyleraharrison** [comment]
This issue should be reopened. I can reproduce on Pop OS and the drivers did not fix anything

**Comment by MrCrayfish** [comment]
Even if I reopen, I can't do anything because the report points to GLFW. I recommend just switching to a different controller if you have the option.

**Comment by tyleraharrison** [comment]
> Even if I reopen, I can't do anything because the report points to GLFW. I recommend just switching to a different controller if you have the option.

Oddly enough, this issue does not happen while wired. I will double check the stacktrace later

**Comment by Volker-Weissmann** [comment]
> > Even if I reopen, I can't do anything because the report points to GLFW. I recommend just switching to a different controller if you have the option.
> 
> Oddly enough, this issue does not happen while wired. I will double check the stacktrace later

Same here, it works if I use a cable.

**Comment by AVonGauss** [comment]
I know the previous entries have said they tried the drivers, but the symptoms (crash, works wired) describe the issue I've also encountered when using the standard Linux driver.  I would double check that you're truly using xpadneo (will rumble on start) or xow (if using wireless adapter).  I haven't used xpadneo in several months, but it worked well when I did and I definitely know xow works.

**Comment by shymega** [comment]
I'm using `xpadneo`, as I connect to my controller via Bluetooth. Haven't tried wired yet, will give that a go later on today. I can't see the standard Linux driver loaded into the kernel.

**Comment by tyleraharrison** [comment]
> I know the previous entries have said they tried the drivers, but the symptoms (crash, works wired) describe the issue I've also encountered when using the standard Linux driver. I would double check that you're truly using xpadneo (will rumble on start) or xow (if using wireless adapter). I haven't used xpadneo in several months, but it worked well when I did and I definitely know xow works.

I tried both, xpadneo does the rumble. Not sure what xow is supposed to do but I got a small vibration different from xpadneo. Is there a way to check if I'm still hooked into the standard Linux drivers?

**Comment by TobiPeterG** [comment]
Hey guys, I'm on OpenSUSE Tumbleweed and the controller virtual mouse controls the "real" courser as well.
I'm using a XBox One Controller with the xow driver.

Can someone confirm this issue?

**Comment by shymega** [comment]
@TobiPeterG Sounds like a different issue to the one here - maybe create a different report?

**Comment by TobiPeterG** [comment]
> @TobiPeterG Sounds like a different issue to the one here - maybe create a different report?


Yeah, ofc, just wanted to hear if someone can confirm that issue before I open a new thread and nobody has that issue. :D

**Comment by shymega** [comment]
> > @TobiPeterG Sounds like a different issue to the one here - maybe create a different report?
> 
> Yeah, ofc, just wanted to hear if someone can confirm that issue before I open a new thread and nobody has that issue. :D

Sure, its just that this issue is about crashes with the xbox one controller, and your issue is completely different...

**Comment by shymega** [comment]
Anyway, I'm installing openSUSE Tumbleweed today in fact. So I'll see if my issue is then resolved. I need to find a way to check if the kernel-provided xbox driver is loaded though.

**Comment by TobiPeterG** [comment]
> > > @TobiPeterG Sounds like a different issue to the one here - maybe create a different report?
> > 
> > Yeah, ofc, just wanted to hear if someone can confirm that issue before I open a new thread and nobody has that issue. :D
> 
> Sure, its just that this issue is about crashes with the xbox one controller, and your issue is completely different... 

Yeah, I know. It's just that there's a chance that none of you would have seen that new issue and there're not soo many people using Linux for Minecraft gaming, so I thought, maybe one of you had the same problem and could confirm it or had the same issue and know a fix I just didn't think of.
And a whole bug report for "you have to do "... "" to fix it would have been unnecessary.

Ofc, creating a bug report for that would have been the correct way and if nobody else comments that he had that issue / knows how to fix it in the next few hours, I'll create a report, don't worry. ;)
Didn't want to bother you, sorry.

**Comment by TobiPeterG** [comment]
> Anyway, I'm installing openSUSE Tumbleweed today in fact. So I'll see if my issue is then resolved. I need to find a way to check if the kernel-provided xbox driver is loaded though.

Oh OK, thank you. It might be important to say that I'm using KDE, that may be related to the issue I had.
Don't know though what you're planning to install.

**Comment by shymega** [comment]
> > > > @TobiPeterG Sounds like a different issue to the one here - maybe create a different report?
> > > 
> > > 
> > > Yeah, ofc, just wanted to hear if someone can confirm that issue before I open a new thread and nobody has that issue. :D
> > 
> > 
> > Sure, its just that this issue is about crashes with the xbox one controller, and your issue is completely different...
> 
> Yeah, I know. It's just that there's a chance that none of you would have seen that new issue and there're not soo many people using Linux for Minecraft gaming, so I thought, maybe one of you had the same problem and could confirm it or had the same issue and know a fix I just didn't think of.
> And a whole bug report for "you have to do "... "" to fix it would have been unnecessary.
> 
> Ofc, creating a bug report for that would have been the correct way and if nobody else comments that he had that issue / knows how to fix it in the next few hours, I'll create a report, don't worry. ;)
> Didn't want to bother you, sorry.

Don't worry about it :smile:

**Comment by shymega** [comment]
> > Anyway, I'm installing openSUSE Tumbleweed today in fact. So I'll see if my issue is then resolved. I need to find a way to check if the kernel-provided xbox driver is loaded though.
> 
> Oh OK, thank you. It might be important to say that I'm using KDE, that may be related to the issue I had.
> Don't know though what you're planning to install.

I was on Arch, but I miss `zypper`. Also, I moved to Arch to try and fix an issue I had with my USB-C dock and the kernel (newer version), but think I've found the bug..

**Comment by TobiPeterG** [comment]
> > > Anyway, I'm installing openSUSE Tumbleweed today in fact. So I'll see if my issue is then resolved. I need to find a way to check if the kernel-provided xbox driver is loaded though.
> > 
> > Oh OK, thank you. It might be important to say that I'm using KDE, that may be related to the issue I had.
> > Don't know though what you're planning to install.
> 
> I was on Arch, but I miss `zypper`. Also, I moved to Arch to try and fix an issue I had with my USB-C dock and the kernel (newer version), but think I've found the bug..

Is the kernel on Arch really that much newer? O.o
Afaik the newest version is 5.6-16 I think and Tumbleweed has 5.6-12 when I remember correctly.
However, the important thing is that you found the bug. ;)

Ps: zypper's great, but I'd like to have a build in option to search the obs. :D
