### ISSUE TITLE
"Swap Hands" or "Swap Item In Hands"?

### ISSUE THREAD

**Issue by TheDirectorX** [MrCrayfish/Controllable#67]
https://github.com/MrCrayfish/Controllable/blob/7f6240c4d0a5ba2842753a3eeb13aad9fce12614/src/main/resources/assets/controllable/lang/en_us.json#L13

Line from `en_us.json` in **Vanilla Minecraft:**

![image](https://user-images.githubusercontent.com/43481085/76352061-40810a00-6330-11ea-916a-1d52c8d0b926.png)

**Comment by MrCrayfish** [comment]
Swap Item In Hands
