### ISSUE TITLE
Crash by entering the world

### ISSUE THREAD

**Issue by agentwolf88** [MrCrayfish/Controllable#69]
When i connect to my world the game is crashing

MC 1.12.2
Latest Forge

https://paste.ee/p/awGoG

**Comment by WotblitzMC** [comment]
Paste not found!

**Comment by xBlackVortex** [comment]
same problem

**Comment by Mydas-Drift** [comment]
I have this problem too
Controllable does not work with Obfuscate
which is the dependence of Vehicles and Guns
Without Obfuscate, Controllable works

**Comment by maham** [comment]
Same. Crash when entering world. Both SP and MP.

Controller: XBox360
Modpack: Uncle Genny's
MC: 1.12.2
Forge: 14.23.5.2854
Controllable: 0.8.0
Weather: Overcast with some rain
Pastebin: https://pastebin.com/C0zUAfYk

**Comment by MrCrayfish** [comment]
Unfortuantely I don't support 1.12 anymore but this is an issue between the Gun Mod and Contollable. You'll want to downgrade to anything before 0.8.0 for it to be fixed.
