### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by Spyeedy** [MrCrayfish/Controllable#7]
The game crashes when I click on the **Select** button with no controllers listed.

Crash report is attached.

[crash-2019-04-01_12.58.27-client.txt](https://github.com/MrCrayfish/Controllable/files/3027822/crash-2019-04-01_12.58.27-client.txt)

**Comment by comp500** [comment]
This is fixed by #2

**Comment by MrCrayfish** [comment]
Fixed in 0.5.0 on 1.14.4 but I will patch for 1.12.2 soon.
