### ISSUE TITLE
Courser won't cover the whole screen

### ISSUE THREAD

**Issue by SevenCone364156** [MrCrayfish/Controllable#72]
I am using the latest version of controllable (1.15.2) and I am using a wired Xbox 1S controller, but my courser will not move away from a quarter of the screen.

**Comment by rryanparkerr** [comment]
I've got the same issue with a PS4 controller.

**Comment by agentwolf88** [comment]
semi solution: disabled Virtual Mouse in settings.

**Comment by MrCrayfish** [comment]
Are you using Optifine? If so, uninstall. Optifine is not 100% compatible with Forge.

**Comment by lienzz** [comment]
I've got the same issue with macOS 10.15.4, wired Xbox One controller and Minecraft 1.15.2. The cursor UI only covers the top left quarter of the screen. The cursor itself seems to cover the entire screen but it looks like there is a mismatch. Screenshot: https://pasteboard.co/J985Vi9.png

**Comment by DankTooki** [comment]
> semi solution: disabled Virtual Mouse in settings.

I tried this but the cursor will go back to the last spot it was when there's a new input with the joystick.

**Comment by MrCrayfish** [comment]
Closing this issue due to it being stale. Reopen a new issue if this is still a problem in the latest version.
