### ISSUE TITLE
Analog issue

### ISSUE THREAD

**Issue by SouthernPixel** [MrCrayfish/Controllable#74]
Im using the latest version of Controllable for 1.12.2 and the latest version of forge and it was working before perfectly but now it thinks im moving my analog upward and to the right but im not and it only happens when im actually in a game, it doesnt do it in the main menu. Its not my controller either because my friend is getting the same problem. There is a term for this sort of thing but I cant recall what the name is so i apologize

**Comment by MrCrayfish** [comment]
Change the deadzone setting in the controllable settings menu to something higher like 0.15
