### ISSUE TITLE
Impossible to press JEI elements

### ISSUE THREAD

**Issue by HenrikoMagnifico** [MrCrayfish/Controllable#76]
It is currently impossible to hit JEI elements (buttons, search bar, items etc.) using controllable.

**Comment by WotblitzMC** [comment]
That's true. Ether The developer of JEI or MrCrayFish need to implement support.

**Comment by greysondn** [comment]
This is an error, yeah. Not sure who it belongs to. It doesn't bother me as I don't use JEI, but I noticed it when I tried it.

**Comment by JesseGuerrero** [comment]
Id like to see JEI/NEI get implemented

**Comment by MrCrayfish** [comment]
You should not be able ot interact with JEI in the latest version of Controllable.
