### ISSUE TITLE
Picking up an item in the inventory automatically centers it at the cursor and makes it immovable

### ISSUE THREAD

**Issue by HenrikoMagnifico** [MrCrayfish/Controllable#77]
When picking up an item or a stack of items in the inventory, the cursor automatically locks to the center of the screen and does not move unless I move it using the mouse (which defeats the whole point of using a controller).

**Comment by WotblitzMC** [comment]
I'm pretty sure I know what went wrong. May I ask, does the inventory slots react when you hover over them with the virtual controller cursor? Does the white hue appear?

**Comment by DarkSnow07** [comment]
I have the same problem, can someone help me?

**Comment by asadsalman** [comment]
Same issue! Latest Controllable build.

**Comment by MrCrayfish** [comment]
I need MC version, Mod version and Forge version or no help!

**Comment by RedCDev** [comment]
> I need MC version, Mod version and Forge version or no help!

On 0.8.0 I think(latest), and something is wrong with you transformer.js as applyHotbarOffset() is not being injected also on 0.8.0

**Comment by MrCrayfish** [comment]
@RedCDev report on a seperate issue. Do not comment under a random issue as I will not fix it.

Also for everyone else in regards to this issue. The problem is Optifine...

**Comment by HenrikoMagnifico** [comment]
MC 1.12.2.
Forge 14.23.5.2847
Latest Controllable (0.8.0)

Still occurs. Please open up the issue again!

**Comment by HenrikoMagnifico** [comment]
Here is a video of the issue: https://youtu.be/czm1EuWLQCw

**Comment by HenrikoMagnifico** [comment]
Thanks!
