### ISSUE TITLE
Controller HUD Disappears while breaking blocks and standing still

### ISSUE THREAD

**Issue by eamonrw** [MrCrayfish/Controllable#8]
When breaking a block that takes a while to break, or while breaking a tree, if it takes longer than a few seconds, the controller HUD disappears, even though I am still breaking the block with the controller. Maybe the timer for the HUD starts when a button is pressed, instead of when it is released?

**Comment by hoostelstudios** [comment]
That's not an issue or bug. It's the mod's configuration.

**Comment by MrCrayfish** [comment]
This has been fixed in recent versions
