### ISSUE TITLE
Item offset on console hotbar enabled

### ISSUE THREAD

**Issue by RedCDev** [MrCrayfish/Controllable#80]
I noticed that your coremod couldn't patch in the "applyHotbarOffset()" method.
This is a raw copy of the log:
[controllable-transformer.js] Patching IngameGui...
[controllable-transformer.js] Failed to find method: net.minecraft/client/gui/IngameGui#renderSelectedItem()V

And it seems that it didn't work on ForgeIngameGui either.

**Comment by MrCrayfish** [comment]
Can you tell me the Forge version, Minecraft version and Mod version you are using?

**Comment by MrCrayfish** [comment]
This is fixed in newer versions!
