### ISSUE TITLE
My dualshock 4 is not detected by controllable

### ISSUE THREAD

**Issue by a2Tap** [MrCrayfish/Controllable#84]
Hi, firstly thanks for this amazing mod ! I wanted to connect directly my controller to minecraft but it didn't detect it, I was using DS4 windows but it was showing my controller as PS3/360 so I wanted to connect my controller for remaping.. I tried to use ds4 windows dinput but nothing neither. 
(I connected my controller by USB cable). 
Thanks for your time.

**Comment by pinospin** [comment]
me too
i think that it doesn't support v2 controller, only v1 (can be indicated by looking at the touchpad, if it have a light bar, then it's v2 controller)

**Comment by MrCrayfish** [comment]
You'll need to use a program like DS4Windows to use a PS4 controller. https://github.com/Ryochan7/DS4Windows/releases
