### ISSUE TITLE
Small GUI button issue

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/Controllable#88]
The controllable button doesn't follow the new specifications for buttons and glows instead of being outlined.
![image](https://user-images.githubusercontent.com/19599406/82775384-67fa5580-9dfc-11ea-947b-e30a9f703a37.png)
Other buttons
![image](https://user-images.githubusercontent.com/19599406/82775422-82ccca00-9dfc-11ea-8bcb-86bdca9daf81.png)

**Comment by MrCrayfish** [comment]
F I X E D
