### ISSUE TITLE
crashes when loading an save file

### ISSUE THREAD

**Issue by DarkBenjamin19** [MrCrayfish/Controllable#91]
Can You Pls Fix This Problem

---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  CreativePatchingLoader (CreativeCore-1.12.2.jar)
  Controllable (controllable-1.12.2-0.8.0.jar)
  PlayerAPIPlugin (PlayerAPI-1.12.2-1.0.jar)
  ASMPlugin (Squake-Mod-1.12.2.jar)
  LibrarianLib Plugin (LibrarianLib-1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  McLib core mod (mclib-1.0.4-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/10/20 10:51 PM
Description: Unexpected error

java.lang.NoSuchMethodError: com.mrcrayfish.controllable.client.Controller.getState()Lcom/studiohartman/jamepad/ControllerState;
	at com.mrcrayfish.guns.client.ControllerEvents.onRender(ControllerEvents.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_ControllerEvents_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.guns.client.ControllerEvents.onRender(ControllerEvents.java:174)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_308_ControllerEvents_onRender_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DarkBenjamin19'/786, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 07 - RTG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['DarkBenjamin19'/786, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1107920368 bytes (1056 MB) / 2583691264 bytes (2464 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 7, allocated: 23, tallocated: 114
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 37 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version            | Source                                      | Signature                                |
	|:------ |:-------------------- |:------------------ |:------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2             | minecraft.jar                               | None                                     |
	| LCHIJA | mcp                  | 9.42               | minecraft.jar                               | None                                     |
	| LCHIJA | FML                  | 8.0.99.99          | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCHIJA | forge                | 14.23.5.2847       | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCHIJA | creativecoredummy    | 1.0.0              | minecraft.jar                               | None                                     |
	| LCHIJA | PlayerAPI            | 1.0                | minecraft.jar                               | None                                     |
	| LCHIJA | controllable         | 0.8.0              | controllable-1.12.2-0.8.0.jar               | None                                     |
	| LCHIJA | obfuscate            | 0.4.2              | minecraft.jar                               | None                                     |
	| LCHIJA | vgirlarmor           | 2.9.6              | [1.12.2]+Valtiel+s+Girl+Armor+Mod-2.9.7.jar | None                                     |
	| LCHIJA | rpghud               | 3.6.6.2            | [1.12]+RPG-HUD-3.6.6.2.jar                  | None                                     |
	| LCHIJA | baubles              | 1.5.2              | Baubles-Mod-1.12.2.jar                      | None                                     |
	| LCHIJA | betterswiming        | 1.0.4              | Better-Swiming-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | better_diving        | 1.4.14             | BetterDiving-1.12.2-1.4.14.jar              | None                                     |
	| LCHIJA | carryon              | 1.12.2             | CarryOn+MC1.12.2+v1.12.2.jar                | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHIJA | creativecore         | 1.9.9              | CreativeCore-1.12.2.jar                     | None                                     |
	| LCHIJA | customnpcs           | 1.12               | CustomNPCs_1.12.2-(01Oct19).jar             | None                                     |
	| LCHIJA | ptrmodellib          | 1.0.4              | PTRLib-1.12.2.jar                           | None                                     |
	| LCHIJA | props                | 2.6.3              | DecoCraft-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | orelib               | 3.6.0.1            | OreLib-1.12.2-3.6.0.1.jar                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround            | 3.6.1.0            | DynamicSurroundings-1.12.2-3.6.1.0.jar      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | enhancedvisuals      | 1.0                | EnhancedVisuals_v1.2.4_mc1.12.2.jar         | None                                     |
	| LCHIJA | forgelin             | 1.8.2              | Forgelin-1.8.2.jar                          | None                                     |
	| LCHIJA | cgm                  | 0.15.3             | guns-0.15.3-1.12.2.jar                      | None                                     |
	| LCHIJA | lblades              | 1.0.2              | LegendaryWeapons-V1.0.2.jar                 | None                                     |
	| LCHIJA | librarianlib         | 4.17               | LibrarianLib-1.12.2.jar                     | None                                     |
	| LCHIJA | lostcities           | 2.0.22             | lostcities-1.12-2.0.22.jar                  | None                                     |
	| LCHIJA | joypadsplitscreenmod | 1.12.0-0.22        | MCJoypad-Mod-1.12.2.jar                     | None                                     |
	| LCHIJA | mclib                | 1.0.4              | mclib-1.0.4-1.12.2.jar                      | None                                     |
	| LCHIJA | mjrlegendslib        | 1.12.2-1.1.9       | MJRLegendsLib-1.12.2-1.1.9.jar              | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJA | silentlib            | 3.0.13             | SilentLib-1.12.2-3.0.13+167.jar             | None                                     |
	| LCHIJA | scalinghealth        | 1.3.37             | ScalingHealth-1.12.2-1.3.42+147.jar         | None                                     |
	| LCHIJA | squeedometer         | 1.0.4              | Squeedometer-mc1.12.x-1.0.4.jar             | None                                     |
	| LCHIJA | squake               | 1.0.6              | Squake-Mod-1.12.2.jar                       | None                                     |
	| LCHIJA | tails                | 1.12-1.10.0        | Tails-1.12-1.10.0.jar                       | None                                     |
	| LCHIJA | rtg                  | 6.1.0.0-snapshot.1 | RTG-1.12.2-6.1.0.0-snapshot.1.jar           | None                                     |
	| LCHIJA | librarianliblate     | 4.17               | LibrarianLib-1.12.2.jar                     | None                                     |
	| UD     | mclib_core           | 1.0.4              | minecraft.jar                               | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
CreativePatchingLoader (CreativeCore-1.12.2.jar)
  
Controllable (controllable-1.12.2-0.8.0.jar)
  com.mrcrayfish.controllable.asm.ControllableTransformer
PlayerAPIPlugin (PlayerAPI-1.12.2-1.0.jar)
  api.player.forge.PlayerAPITransformer
ASMPlugin (Squake-Mod-1.12.2.jar)
  squeek.quakemovement.ASMPlugin
LibrarianLib Plugin (LibrarianLib-1.12.2.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 442.92' Renderer: 'GeForce GTX 1080 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.92, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: More Spooky Cave Sounds (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-1.0.0 (2).zip
	OpenGlVersion: 4.6.0 NVIDIA 442.92
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by MrCrayfish** [comment]
The gun mod for 1.12 isn't compatible with the latest version of controllable.

**Comment by MrCrayfish** [comment]
Please report to the gun mod repo
