### ISSUE TITLE
Minecraft controllable 8.0.0 Crash! can you fix the bug?

### ISSUE THREAD

**Issue by Nartzify** [MrCrayfish/Controllable#94]
The game crashed whilst the unexpected error
Error: java.lang.NoSuchMethodError: com.mrcrayfish.controllable.client.Controller.getState()Lcom/studiohartman/jamepad/ControllerState;

It happens when I use 1.12.2 forge with these mods :
cgm-0.15.3-mc1.12.2 (1)
grapplemod-v11.1-1.12.2
bookworm-1.12.2-2.5.1
zawa-1.12.2-2.0.35
obfuscate-0.2.6-1.12.2
ShoulderSurfing-1.12.2-1.15
sit-1.12.x-v1.1.2
vehicle-0.43.4-mc1.12.2
BetterFps-1.4.8
RealFirstPerson2-1.12.2-1.3.2
mobends-0.24_for_MC-1.12
controllable-0.8.0-mc1.12.2
preview_OptiFine_1.12.2_HD_U_F6_pre1

**Comment by MrCrayfish** [comment]
The latest version of controllable is not compatible with the latest version of the gun mod (on 1.12.2)

**Comment by Nartzify** [comment]
I remove the gun mod, and it's still not working. the crash report is the same

**Comment by MrCrayfish** [comment]
Download the latest vehicle mod

**Comment by Nartzify** [comment]
okay, anyway which gun mod version that I can use in this problem?

**Comment by MrCrayfish** [comment]
You need to downgrade Controllable

**Comment by Nartzify** [comment]
no please :( I still need to use the latest your other mods, your mods are awesome seriously all of them, it's so fun to play with my brother in this quarantine with controllable and all of your mods, except the gun mod. please tell me which version of the gun mod, I've tried to figure it out, but I can't find it that the one who's work.

**Comment by Nartzify** [comment]
I like you so much since the first version of furniture mod that you've been created. that's made my gold year
