### ISSUE TITLE
Rainway drift(possiblely nothing)(solved?) 

### ISSUE THREAD

**Issue by UnknownDev37** [MrCrayfish/Controllable#98]
**WARNING, this post is to make sure that this could be a bug but as of writing this my problem was fixed for now. Go ahead and close if you want but I wanted to make sure if anyone else had the same problem they could see this.**
_While using a program called rainway (Parsec alternative) player slowly looks down. In menus, it is fine, only when playing.|
Controller is named "ShanWan Ps3/PC Wired Gamepad"
 ... I found a workaround, I turned off Rainway controller witch Disables Virtual Controller, Big brain went small because toggling that fixed my problem? I have turned off my pc before posting this so at this point I have no clue... 
I guess if you can reproduce the problem good for you if not it's fine. could be bad luck or a rare bug._
**HOW I FIXED MY DRIFT
Step one, Toggle Rainway controller in settings(on and off)
Step two, Magically Fixed? Got to love computers**

**Comment by MrCrayfish** [comment]
Change the deadzone...
